### ISSUE TITLE
Port STM32F412 Discovery board

### ISSUE THREAD

**Issue by hathach** [hathach/tinyusb#103]
**Porting layer**
 - [ ] Device Controller Driver (DCD)
 - [ ] Host Controller Driver (HCD)
 - [x] Board Supported Package (BSP)
 - [ ] OS Abstraction Layer (OSAL)

**Comment by ladyada** [comment]
@hathach please try to finish this next since we have circuitpython working other than USB so this is the only step :)

**Comment by hathach** [comment]
@ladyada yeah, got the board blinky, but the usb somehow isn't regconzied. troubleshooting it asap.

**Comment by hathach** [comment]
closed by #120

**Comment by ladyada** [comment]
i tried with great success - here's the bin from thach

be sure to install a jumper into the **JP3** USB jumper, its near the green **PWR** LED
[stm32f412disco.zip](https://github.com/hathach/tinyusb/files/3588803/stm32f412disco.zip)
