### ISSUE TITLE
tud_vendor_write_available

### ISSUE THREAD

**Issue by southpawbob** [hathach/tinyusb#105]
I need to be able to write to the USB vendor device when I know the FIFO has room for the data I'd like to send. "tud_cdc_write_available" is a great solution for the CDC device, I'd like something similar for vendor writes. If there is a different way to achieve this, I wasn't able to figure it out.

**Comment by hathach** [comment]
it is still useful to have an API, e.g you don't have half of your message in the fifo. I will add it later on
