### ISSUE TITLE
How to get nRF52840 to communicate with browser via webusb using TinyUSB?

### ISSUE THREAD

**Issue by armsp** [hathach/tinyusb#106]
I don't have a lot of experience with embedded devices and I am asking this question as a last resort after no replies on SO and Adafruit forum.

Recently I got a SAMD21 board to interact with browser via webusb in 2 ways-
1. Selecting `Arduino` from `USB Stack` with the help of arduino [webusb](https://github.com/webusb/arduino) library 
2. Selecting `TinyUSB` from `USB Stack` with the help of [Adafruit_TinyUSB_Arduino](https://github.com/adafruit/Adafruit_TinyUSB_Arduino) library

Now, arduino webusb [doesn't support](https://github.com/webusb/arduino#compatible-hardware) nRF52840 so far. However TinyUSB [does](https://github.com/hathach/tinyusb#supported-mcus).  

**NOTE:** I **don't** have the [supported](https://github.com/hathach/tinyusb/blob/master/docs/boards.md#nordic-nrf5x) boards for nR52840 , instead I have the latest Arduino Nano 33 BLE

So I was wondering how should I go about making my nRF52840 board communicate with browser?  
    The TinyUSB files don't make any sense to me right now. Nor can I make sense of running the webusb example. When I run `make Makefile BOARD="feather_nrf52840_express"` it outputs -
`make: Nothing to be done for 'Makefile'`.  
I chose `feather_nrf52840_express` as BOARD since the code isn't using any hardware pins so it doesn't matter if the board definitions are wrong. Just the internal core should be okay. But it doesn't work.

I tried another method too -  
I ran the given [webusb examples](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/tree/master/examples) of Adafruit_TinyUSB_Arduino but they fail to upload on Nano 33 BLE.

I don't know much about why...perhaps its the mbed core it uses and you have a different core for nRF52 devices ? Or maybe the bootloader is different than what you expect ?

I don't necessarily want ready baked answers, I am willing to put in my time and effort. Just need some guidance and right direction on where should I look and what files should I write or will be helpful for this.

**Comment by hathach** [comment]
It is inappropriate repo to ask this question. Arduino TinyUSB port work with `Adafruit Feather nRF52840`, get one or try to port it to your board.
