### ISSUE TITLE
/examples/host/hid_controller is not compiled

### ISSUE THREAD

**Issue by csBlueChip** [hathach/tinyusb#1067]
### Operating System

Linux

### Board

RP2040

### Firmware

/examples/host/hid_controller

### What happened ?

hid_controller does not build ...because `/examples/host/CMakeLists.txt` lacks the line `family_add_subdirectory(hid_controller)`

### How to reproduce ?

* `mkdir ~/tmp ; cd ~/tmp`
* `cmake -DFAMILY=rp2040 /path/to/tinyusb/examples`
...note that hid_controller is not built

### Debug Log

n/a

**Comment by hathach** [comment]
since you already know how to fix it, would you mind making an PR to fix this ?

**Comment by csBlueChip** [comment]
I am trying to write two new class host drivers (by reverse engineering the existing driver code) ...When I have done that, I will need to learn how Git PRs work ...So my answer is: Yes, but give me time ;)
