### ISSUE TITLE
CDC dual port example always echos between ports, but nothing to do with 'cdc_task()'

### ISSUE THREAD

**Issue by mws-rmain** [hathach/tinyusb#1148]
### Operating System

Windows 10

### Board

Curiosity Nano (ATSAMD21G17D)

### Firmware

examples/device/cdc_dual_ports

### What happened ?

The CDC dual port example is supposed to 'echo' received characters from either port to both ports (lower case to one port, upper case to other port).
When I connect my 'curiosity nano' board (ATSAMD21G17D) to a Windows 10 PC, two additional Comm ports are visible after it enumerates. I open two instances of 'TeraTerm', one attached to each port. TeraTerm is configured (/setup/terminal) with local echo enabled, so anything typed into a terminal window appears in that window, so when I type into either window, I should see:
- in the active TT window, the character I typed (due to TT 'local echo')
- in the active TT window, the character I typed (due to CDC echo back), which may be either upper or lower case (depending on which port the terminal is connected to.
- in the OTHER TT window, the character I typed, which will the the opposite case compared to the second character appearing in the active TT window.

What I see is:
- in the active TT window, the character I typed (due to TT 'local echo')
- in the OTHER TT window, the character I typed (no case changed regardless of which window is 'active').

In the example/device/cdc_dual_ports/src/main.c file, I commented out the call to 'cdc_task()' at line 50, and bracketed lines 55-104 (end-of-file) in "#if 0"/"#endif" so it would compile. The two serial ports still enumerate when connected to my PC, and the behavior of the ports is identical to that above (i.e., echoing of data entered into one port is NOT dependant on the code in "cdc_task() & echo_serial_port()" in main.c, but appear to be occuring somewhere within the TinyUSB itself since only tud_task() is called within the main loop.

I originally added TinyUSB to my own project, but had problems connecting a USB/CDC port to a physical UART. My equivalent 'cdc_task()' routine never received any data (from TT via USB), and I verified data was received by my physical UART and sent to TinyUSB (tud_cdc_n_write()), but was never received into the connected terminal.

I returned to the cdc_dual_ports example in order to start from a codebase with known 'expected behavior' (so much for that ;-)

Any suggestions for further diagnosis?

The most surprising thing for me was that the cdc_dual_ports example was echoing data from one port to the other when _only_ the 'tud_task()' was called in a loop.

### How to reproduce ?

To reproduce:
1. Build the CDC_DUAL_PORTS example (maybe ensure this is done on a SAMD21 board?)
2. Burn the example into the target
3. Connect the target board to a windows PC. Verify two additional COMM PORTS appear (& note the numbers)
4. Open two TeraTerm terminals (one connected to each port from above). My settings were for 115200,8,1,n (shouldn't matter). Note the setting for 'local echo' - if enabled, any character entered will echo to the active terminal by the program (so don't assume this is coming from TinyUSB on the target. Try typing into each terminal, upper case & lower case. Verify the active terminal always displays what is typed (in same case), and same appears in 'other' terminal.

**Comment by hathach** [comment]
> The most surprising thing for me was that the cdc_dual_ports example was echoing data from one port to the other when only the 'tud_task()' was called in a loop.

This is 100% not the case, could you check
- how did you compile the code, ?make sure you `make clean` first when modify the code and 
- double check the flashing process or flash contents.
