### ISSUE TITLE
TUD_HID_REPORT_DESC_GAMEPAD comment outdated

### ISSUE THREAD

**Issue by chegewara** [hathach/tinyusb#1199]
### Operating System

Others

### Board

all

### Firmware

hid gamepad

### What happened ?

Sorry for complaining, but this comment is a bit old and misleading and HID gamepad descriptor does not match it.
Currently descriptor is built for 32 buttons.

### How to reproduce ?

https://github.com/hathach/tinyusb/blob/master/src/class/hid/hid_device.h#L313-L314

**Comment by hathach** [comment]
right, it is out dated, would you mind making an PR to correct it ?
