### ISSUE TITLE
Add a winusb example

### ISSUE THREAD

**Issue by Kevincoooool** [hathach/tinyusb#1230]
**Is your feature request related to the problem? Please describe. **
A clear and concise description of the problem. predecessor. I always feel frustrated when [...]
Hello, I am currently using esp32s3 as a DAPLink debugger, it works normally when using HID, but I want to use WIFI as a wireless debugger, but when using HID with WIFI TCP, it is very slow because of the 1ms limit of HID , So I thought of the winusb daplink, I tried to modify the webusb_serial example, but win10 cannot recognize the device as a winusb device, and an exclamation mark appears, so can you add a winusb example? Thank you!
**Describe the solution you want**
I think the webusb example can be slightly modified, and the option of winusb can be added.

**Comment by hathach** [comment]
No, we cannot have an example for every user scenario or class driver combination. I don't have enough time to maintain them all. Besides webusb example already did exactly `binding winUSB` driver. If you have issue problem to get it work, you could open an discussion providing all your setup/code and what is your issue/finding, maybe people that already done that could help.
