### ISSUE TITLE
Add USBTMC class device implementation

### ISSUE THREAD

**Issue by pigrew** [hathach/tinyusb#129]
I would like a USBTMC class implementation, with USBTMC USB488 features. This request is only for a device-side driver.

Implementing this class was my reason to start working on tinyusb; I have not been able to find an open source USBTMC device implementation (and many closed source ones do not conform to the standard's, like Siglent's).

(I've started working on it, but won't promise anything).

**Comment by hathach** [comment]
thanks for issue, I am new to this class, I will also check to see if I could get some stubs for you. So that you don't have to read the whole stack.

**Comment by pigrew** [comment]
It's actually very similar to CDC. I'll start with the CDC as a base. It mostly uses control transfers on EP0 to queue traffic on bulk. I think that interrupt endpoints may be used, too.

**Comment by pigrew** [comment]
I'm closing this issue, as we've merged the patch. Yay. (PR #160 )

**Comment by hathach** [comment]
Thanks for your amazing works :)
