### ISSUE TITLE
Unable to build cdc_msc_freertos (ESP32S2)

### ISSUE THREAD

**Issue by AleshR** [hathach/tinyusb#1310]
### Operating System

Linux

### Board

ESP32-S2-Saola-1R

### Firmware

ESP-IDF v5.0-dev-1437-gb092fa0730

### What happened ?

I am trying few days cdc_msc_freertos to get working.  Unfortunately I'm not able to build example project.
I followed up this pull request: https://github.com/hathach/tinyusb/pull/319

So I am able to build every example (yes, hello worl was first where i started) but cdc_msc_freertos I am not...

`idf.py build` not working properly... so I tried `idf.py -DFAMILY=esp32s2 build`

My little tip is problem with linker or something like this. But it's first time i see this problem so i don´t know, how to fix it.

Thank you for your time and sorry for my english...

### How to reproduce ?

Simply clone latest version of tinyusb and go to: tinyusb/examples/device/cdc_msc_freertos
Then run `idf.py build`

In my case, i see log below. 

After few experiments i tried:
`idf.py -DFAMILY=esp32s2 build`
and it looks like a good way, but still i have error message (second part of Debug Log)

### `idf.py build`

idf.py build    
Executing action: all (aliases: build)
Running cmake in directory /home/alesh/esp/tinyusb/examples/device/cdc_msc_freertos/build
Executing "cmake -G 'Unix Makefiles' -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DCCACHE_ENABLE=0 /home/alesh/esp/tinyusb/examples/device/cdc_msc_freertos"...
CMake Error at /home/alesh/esp/tinyusb/hw/bsp/family_support.cmake:5 (message):
  You must set a FAMILY variable for the build (e.g.  rp2040, eps32s2,
  esp32s3).  You can do this via -DFAMILY=xxx on the camke command line
Call Stack (most recent call first):
  CMakeLists.txt:8 (include)

-- Configuring incomplete, errors occurred!
cmake failed with exit code 1

---
### `idf.py -DFAMILY=esp32s2 build`

idf.py -DFAMILY=esp32s2 build                                                                                 
Executing action: all (aliases: build)
Running cmake in directory /home/alesh/esp/tinyusb/examples/device/cdc_msc_freertos/build
Executing "cmake -G 'Unix Makefiles' -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DFAMILY=esp32s2 -DCCACHE_ENABLE=0 /home/alesh/esp/tinyusb/examples/device/cdc_msc_freertos"...
-- IDF_TARGET not set, using default target: esp32
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/alesh/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/alesh/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/alesh/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32
-- Project sdkconfig file /home/alesh/esp/tinyusb/examples/device/cdc_msc_freertos/sdkconfig
Loading defaults file /home/alesh/esp/tinyusb/examples/device/cdc_msc_freertos/sdkconfig.defaults...
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of time_t
-- Check size of time_t - done
-- Found Python3: /home/alesh/.espressif/python_env/idf5.0_py3.9_env/bin/python3.9 (found version "3.9.9") found components: Interpreter 
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPython/Support.cmake:3188 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "PROJECT" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPython3.cmake:485 (include)
  /home/alesh/esp/esp-idf/components/mbedtls/mbedtls/CMakeLists.txt:90 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS - Success
-- App "cdc_msc_freertos" version: 0.12.0-316-gd6fb1859
-- Adding linker script /home/alesh/esp/tinyusb/examples/device/cdc_msc_freertos/build/esp-idf/esp_system/ld/memory.ld
-- Adding linker script /home/alesh/esp/esp-idf/components/esp_system/ld/esp32/sections.ld.in
-- Adding linker script /home/alesh/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.ld
-- Adding linker script /home/alesh/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.api.ld
-- Adding linker script /home/alesh/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.libgcc.ld
-- Adding linker script /home/alesh/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-data.ld
-- Adding linker script /home/alesh/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.syscalls.ld
-- Adding linker script /home/alesh/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld
-- Adding linker script /home/alesh/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-time.ld
-- Adding linker script /home/alesh/esp/esp-idf/components/soc/esp32/ld/esp32.peripherals.ld
CMake Error at /home/alesh/esp/tinyusb/hw/bsp/esp32s2/boards/CMakeLists.txt:7 (include):
  include could not find requested file:

    /board.cmake

-- Components: app_trace app_update asio boards bootloader bootloader_support bt cmock coap console cxx driver efuse esp-tls esp32 esp_adc_cal esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_lcd esp_local_ctrl esp_netif esp_phy esp_pm esp_ringbuf esp_rom esp_serial_slave_link esp_system esp_timer esp_websocket_client esp_wifi espcoredump esptool_py fatfs freemodbus freertos hal heap http_parser idf_test ieee802154 json led_strip log lwip mbedtls mdns mqtt newlib nvs_flash openssl openthread partition_table perfmon protobuf-c protocomm pthread sdmmc soc spi_flash spiffs src tcp_transport tcpip_adapter tinyusb ulp unity usb vfs wear_levelling wifi_provisioning wpa_supplicant xtensa
-- Component paths: /home/alesh/esp/esp-idf/components/app_trace /home/alesh/esp/esp-idf/components/app_update /home/alesh/esp/esp-idf/components/asio /home/alesh/esp/tinyusb/hw/bsp/esp32s2/boards /home/alesh/esp/esp-idf/components/bootloader /home/alesh/esp/esp-idf/components/bootloader_support /home/alesh/esp/esp-idf/components/bt /home/alesh/esp/esp-idf/components/cmock /home/alesh/esp/esp-idf/components/coap /home/alesh/esp/esp-idf/components/console /home/alesh/esp/esp-idf/components/cxx /home/alesh/esp/esp-idf/components/driver /home/alesh/esp/esp-idf/components/efuse /home/alesh/esp/esp-idf/components/esp-tls /home/alesh/esp/esp-idf/components/esp32 /home/alesh/esp/esp-idf/components/esp_adc_cal /home/alesh/esp/esp-idf/components/esp_common /home/alesh/esp/esp-idf/components/esp_eth /home/alesh/esp/esp-idf/components/esp_event /home/alesh/esp/esp-idf/components/esp_gdbstub /home/alesh/esp/esp-idf/components/esp_hid /home/alesh/esp/esp-idf/components/esp_http_client /home/alesh/esp/esp-idf/components/esp_http_server /home/alesh/esp/esp-idf/components/esp_https_ota /home/alesh/esp/esp-idf/components/esp_https_server /home/alesh/esp/esp-idf/components/esp_hw_support /home/alesh/esp/esp-idf/components/esp_lcd /home/alesh/esp/esp-idf/components/esp_local_ctrl /home/alesh/esp/esp-idf/components/esp_netif /home/alesh/esp/esp-idf/components/esp_phy /home/alesh/esp/esp-idf/components/esp_pm /home/alesh/esp/esp-idf/components/esp_ringbuf /home/alesh/esp/esp-idf/components/esp_rom /home/alesh/esp/esp-idf/components/esp_serial_slave_link /home/alesh/esp/esp-idf/components/esp_system /home/alesh/esp/esp-idf/components/esp_timer /home/alesh/esp/esp-idf/components/esp_websocket_client /home/alesh/esp/esp-idf/components/esp_wifi /home/alesh/esp/esp-idf/components/espcoredump /home/alesh/esp/esp-idf/components/esptool_py /home/alesh/esp/esp-idf/components/fatfs /home/alesh/esp/esp-idf/components/freemodbus /home/alesh/esp/esp-idf/components/freertos /home/alesh/esp/esp-idf/components/hal /home/alesh/esp/esp-idf/components/heap /home/alesh/esp/esp-idf/components/http_parser /home/alesh/esp/esp-idf/components/idf_test /home/alesh/esp/esp-idf/components/ieee802154 /home/alesh/esp/esp-idf/components/json /home/alesh/esp/tinyusb/hw/bsp/esp32s2/components/led_strip /home/alesh/esp/esp-idf/components/log /home/alesh/esp/esp-idf/components/lwip /home/alesh/esp/esp-idf/components/mbedtls /home/alesh/esp/esp-idf/components/mdns /home/alesh/esp/esp-idf/components/mqtt /home/alesh/esp/esp-idf/components/newlib /home/alesh/esp/esp-idf/components/nvs_flash /home/alesh/esp/esp-idf/components/openssl /home/alesh/esp/esp-idf/components/openthread /home/alesh/esp/esp-idf/components/partition_table /home/alesh/esp/esp-idf/components/perfmon /home/alesh/esp/esp-idf/components/protobuf-c /home/alesh/esp/esp-idf/components/protocomm /home/alesh/esp/esp-idf/components/pthread /home/alesh/esp/esp-idf/components/sdmmc /home/alesh/esp/esp-idf/components/soc /home/alesh/esp/esp-idf/components/spi_flash /home/alesh/esp/esp-idf/components/spiffs /home/alesh/esp/tinyusb/examples/device/cdc_msc_freertos/src /home/alesh/esp/esp-idf/components/tcp_transport /home/alesh/esp/esp-idf/components/tcpip_adapter /home/alesh/esp/esp-idf/components/tinyusb /home/alesh/esp/esp-idf/components/ulp /home/alesh/esp/esp-idf/components/unity /home/alesh/esp/esp-idf/components/usb /home/alesh/esp/esp-idf/components/vfs /home/alesh/esp/esp-idf/components/wear_levelling /home/alesh/esp/esp-idf/components/wifi_provisioning /home/alesh/esp/esp-idf/components/wpa_supplicant /home/alesh/esp/esp-idf/components/xtensa
-- Configuring incomplete, errors occurred!
See also "/home/alesh/esp/tinyusb/examples/device/cdc_msc_freertos/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1

**Comment by hathach** [comment]
It is mentioned in the https://github.com/hathach/tinyusb/blob/master/docs/reference/getting_started.rst

```
make BOARD=Your-board
```
