### ISSUE TITLE
tud_cdc_get_line_coding() returns void

### ISSUE THREAD

**Issue by pigrew** [hathach/tinyusb#132]
tud_cdc_get_line_coding() (cdc_device.h:136) return a value, but is marked as void.

`static inline void tud_cdc_get_line_coding (cdc_line_coding_t* coding)
{
  return tud_cdc_n_get_line_coding(0, coding);
}`

I'm not sure if it should be void or not...

**Comment by hathach** [comment]
right, I will fix it, copy & paste is not very good technique :smile:
