### ISSUE TITLE
Definition of HID_REPORT_ID_N missing the 2nd parameter

### ISSUE THREAD

**Issue by ReeceWeb** [hathach/tinyusb#1329]
### Operating System

Others

### Board

Not hardware specific

### Firmware

No custom firmware present

### What happened ?

This line in src/class/hid/hid.h is incorrect:
#define HID_REPORT_ID_N(x)        HID_REPORT_ITEM(x, RI_GLOBAL_REPORT_ID, RI_TYPE_GLOBAL, n),

It should read:
#define HID_REPORT_ID_N(x, n)      HID_REPORT_ITEM(x, RI_GLOBAL_REPORT_ID, RI_TYPE_GLOBAL, n),

### How to reproduce ?

Source inspection

**Comment by hathach** [comment]
thank you for reporting this issue, it will be fixed by #1330
