### ISSUE TITLE
tusb_option.h - Error during host build

### ISSUE THREAD

**Issue by yoyopod** [hathach/tinyusb#1359]
### Operating System

Others

### Board

Custom NXP i.MX1064 RT board w/ FreeRTOS

### Firmware

The tusb_option.h file causes an error during a host build because the #define of TUD_OPT_HIGH_SPEED uses TUD_OPT_RHPORT as a shift value.  TUD_OPT_RHPORT is set to -1 for host-mode builds.

A likely fix would be to condition the #define of TUD_OPT_HIGH_SPEED on CFG_TUD_ENABLED (defined on the previous line) evaluating to "true".  I do not want to propose that fix specifically, as I do not have a working knowledge of how all of the various configuration and option values fit and work together.

### What happened ?

This line:

#define TUD_OPT_HIGH_SPEED  ( (TUD_RHPORT_MODE & OPT_MODE_SPEED_MASK) ? (TUD_RHPORT_MODE & OPT_MODE_HIGH_SPEED) : (TUP_RHPORT_HIGHSPEED & (1 << TUD_OPT_RHPORT)) )

produces this error:

"C:\gitlab-erp-use-updated-tinyusb\github\tinyusb\src\tusb_option.h",247  Error[Pe062]:
          shift count is negative
          
I am using the IAR compiler, but I do not believe this error is compiler-specific.

### How to reproduce ?

Build in host mode with no definition for CFG_TUSB_RHPORT0_MODE or CFG_TUSB_RHPORT1_MODE.

**Comment by hathach** [comment]
Thank you for your report, it is due to one of latest changes. I will push a fix soon
