### ISSUE TITLE
__pycache__ directory committed, probably not intentional?

### ISSUE THREAD

**Issue by igrr** [hathach/tinyusb#1408]
### Operating System

Linux

### Board

Any

### Firmware

Haven't compiled yet.

### What happened ?

When cleaning up generated `__pycache__` directories from [esp-idf](https://github.com/espressif/esp-idf) repository tree I've noticed that the tinyusb submodule becomes "dirty" (modified) from git perspective. Turns out that tinyusb includes a Python bytecode file at `hw/mcu/sony/cxd56/tools/__pycache__/xmodem.cpython-36.pyc`. Python bytecode files are usually considered to be local, temporary files and are often added to .gitignore.

I suppose it wasn't committed intentionally; the code in hw/mcu/sony/cxd56/tools/ will work fine without the bytecode file.

Would you consider removing it?

### How to reproduce ?

```
$ git clone https://github.com/hathach/tinyusb
$ find tinyusb -name '__pycache__' | xargs rm -rf
$ git -C tinyusb status
```

### Debug Log as txt file

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    hw/mcu/sony/cxd56/tools/__pycache__/xmodem.cpython-36.pyc

```

**Comment by hathach** [comment]
fixed, thanks for the issue, it is indeed unintended.
