### ISSUE TITLE
dcd_pic32mz.c: line 565

### ISSUE THREAD

**Issue by zj2004** [hathach/tinyusb#1414]
### Operating System

Windows 10

### Board

new MCU port from pic32mz

### Firmware

cdc_msc demo

### What happened ?

the second CBW , bulk out EP got 62 bytes

### How to reproduce ?

sorry for my bad english
my way to fix:
dcd_pic32mz.c: line 565
after xfer_complete(xfer, XFER_RESULT_SUCCESS, true);
add xfer->transferred = 0;

**Comment by hathach** [comment]
please be specific on the MCU, what is your exact MCU and board. Also provide your LOG=2 as attached txt as well.

**Comment by kasjer** [comment]
@zj2004 could you please check if #1451 fixes problem you described?

**Comment by zj2004** [comment]
> @zj2004 could you please check if #1451 fixes problem you described?

yes ，it fixes. 
the problem appear at LOG=2
as you say “For PIC32 OUT packets that were sent from host and not handled fast enough could lead to memory corruption.”
