### ISSUE TITLE
When MDK creates a TingUSB project, it prompts "Compiler attribute porting is required"

### ISSUE THREAD

**Issue by arilink-tech** [hathach/tinyusb#1419]
### Operating System

Windows 10

### Board

STM32 F4

### Firmware

sample/device/cdc

### What happened ?

tusb_compiler.h中   #error "Compiler attribute porting is required"

### How to reproduce ?

Project in CubeIDE After copying TinyUSB related source code to MDK project, the above error is displayed

**Comment by hathach** [comment]
check your cube setup, this is not a bug of this repo

**Comment by arilink-tech** [comment]
It is a problem with the compile-time toolchain. CubeIDE is GCC, MDK is internal AC5, and the problem occurs when using AC5.

**Comment by RickyHe7** [comment]
@arilink I also met this problem. May I ask if you have solved it? 
I have already selected MDK-ARM in CubeMX, but this error occurs when compiling in Keil.
