### ISSUE TITLE
Allow callbacks to have a user pointer for smoother C++ interoperability

### ISSUE THREAD

**Issue by dogtopus** [hathach/tinyusb#1421]
**Is your feature request related to a problem? Please describe.**

Feature request.

I was looking at Adafruit's TinyUSB Arduino library and one thing I noticed is despite the Arduino part is in C++, handling control transfers within a e.g. protocol class for HID is a pain because passing C++ method as a C function pointer is not straightforward. The current construction more or less assumes the class needs to have a (effectively) singleton object and the object reference can be passed either as a static variable within the class or as a global variable, which is ugly and doesn't work well if e.g. the same protocol class needs to be instantiated more than once for any reason. Another possible way out seems to be messing with functional but on embedded compilers especially for microcontrollers, support for this might be a hit or miss.

**Describe the solution you'd like**

Maybe besides the C callback type, have another  callback type that includes a user pointer, so it's possible to do something like `tud_set_some_callback_with_context(&(this->onCallback), this)` in the costructor with onCallback being something like `static void MyClass::onCallback(void *ctx, other params...)`. `ctx` can then be casted back to `MyClass` and it should have access to all the methods and data within that object. It's still kinda ugly looking but at least everything can be handled within the same class without the involvement of (partial) singletons or global variables.

**Comment by hathach** [comment]
can you give example to elaborate the issue.

**Comment by dogtopus** [comment]
One example would be https://github.com/adafruit/Adafruit_TinyUSB_Arduino/blob/master/src/arduino/hid/Adafruit_USBD_HID.cpp

But not looking at it closely, I think it's probably just because of how it's coded to use the USB hardware for HID only, instead of allowing adding/removing protocol handlers, and that the callback names are actually hardcoded in tinyusb and not set by the user.

For the goal I described above I think it would need more code to achieve, and that code will likely not reside in TinyUSB.
