### ISSUE TITLE
Meson build

### ISSUE THREAD

**Issue by perigoso** [hathach/tinyusb#1423]
We might want to switch to a more modern and friendly buildsystem, as the make we have is becoming unwieldy

This is is something I'm willing to work on myself, not wanting to add more burden

until then this serves as a reminder and discussion

**Comment by hathach** [comment]
I have come to desicion that we will use CMake as next build system (existing make should still be supported). It is not CMake is better than meson, but cmake is used more common in embedded e.g CMSIS_5 and FreeRTOS-Kernel, it is just better for us to make use of cmake as well. Thank you for your issue.

PS: Initial CMake is added with https://github.com/hathach/tinyusb/pull/2039 (still more works to do).
