### ISSUE TITLE
Support of STM32H7xx with only 1 USB

### ISSUE THREAD

**Issue by Nikitarc** [hathach/tinyusb#1431]
### Operating System

Windows 10

### Board

NUCLEO-H723ZG

### Firmware

Any firmware

### What happened ?

The STM32H7 family have 2 sub families:
- H74x and H75x have 2 USB, and USB2 have an internal FS PHY. No problem with this sub family.
- H72x, H73x, H7Ax, H7Bx have only 1 USB named USB1 with an internal FS PHY (this USB1 is equivalent to the USB2 of the other sub family). And in the CMSIS files of this sub family the values USB_OTG_FS_PERIPH_BASE and OTG_FS_IRQn are not declared, so the file synopsys/dwc2/dwc2_stm32.h produce compile errors.

This can be solved by adding theses lines to the file dwc2_stm32.h after line 58:
[https://github.com/hathach/tinyusb/blob/master/src/portable/synopsys/dwc2/dwc2_stm32.h#L58](https://github.com/hathach/tinyusb/blob/master/src/portable/synopsys/dwc2/dwc2_stm32.h#L58)

  #if (! defined USB2_OTG_FS)
    // H7 with only 1 USB port: H72x / H73x / H7Ax / H7Bx
    // USB_OTG_FS_PERIPH_BASE and OTG_FS_IRQn not defined in CMSIS files
    #define USB_OTG_FS_PERIPH_BASE  USB1_OTG_HS_PERIPH_BASE
    #define OTG_FS_IRQn             OTG_HS_IRQn
  #endif

Successfully tested on NUCLEO-H723ZG (1 USB) and NUCLEO-H743ZI (2 USB).

### How to reproduce ?

Configure a project for one of this 2nd sub family of the H7.

**Comment by hathach** [comment]
Could you mind making an PR for this change, since I don’t have this board to verify the change.
