### ISSUE TITLE
HID device does not work on STM32H743

### ISSUE THREAD

**Issue by gabrieltetar** [hathach/tinyusb#1445]
### Operating System

Windows 10

### Board

NUCLEO-H743ZI2

### Firmware

irrelevant custom firmware 

### What happened ?

USB HID Device does not appear at all on the host computer

### How to reproduce ?

Issue :
USB HID Device does not appear at all on the host computer

Workaround :
I added some additional bit set before and after your init

In my usb device task :

```
void usb_device_task(void* param)
{
  (void) param;

  SET_BIT(USB_OTG_FS->GUSBCFG, USB_OTG_GUSBCFG_FDMOD); // Default mode is host without this line, it stays host mode
  SET_BIT(USB_OTG_FS->GOTGCTL, USB_OTG_GOTGCTL_BVALOEN); // The PC does not detect the device without this 2 lines
  SET_BIT(USB_OTG_FS->GOTGCTL, USB_OTG_GOTGCTL_BVALOVAL);
  tusb_init();
  SET_BIT(USB_OTG_FS->GOTGCTL, USB_OTG_GOTGCTL_SRQ); // Session request (nothing is going to happen without this line)

  while (1)
  {
    tud_task();
  }
}
```
Also I had to remove this line, it was blocking all of my USB interrupts in tinyusb/src/portable/st/synopsys/dcd_synopsys.c
line 513 :
`//dev->DCFG |=  USB_OTG_DCFG_NZLSOHSK;`

Here is the bit definition, I don't get why it was set and commenting the line fixed the driver
![image](https://user-images.githubusercontent.com/7025023/165124434-277db035-78b0-4af7-8446-6423c355de39.png)

**Comment by Nikitarc** [comment]
tinyusb/src/portable/st/synopsys is obsolete.
You have to use tinyusb/src/portable/synopsys/dwc2.
Do you have the same behavior with dwc2?

**Comment by hathach** [comment]
1. can you verify that this is reproduced with stock example e.g hid_composite to rule out application/set-up issue. 
2. Also as @Nikitarc mentioned above, you should try with the dwc2 driver instead. The st/synopsys will be removed shortly in the future

**Comment by BennyEvans** [comment]
I'm not up to date with the latest version of tinyUSB but have had some experience with this board on an older version. If you take a look in the BSP init function for this platform you'll notice that some of your additions are already present.

For FS: https://github.com/hathach/tinyusb/blob/6ec5174d8b24d1f01a443c74a0a3dbee00523efc/hw/bsp/stm32h7/family.c#L151-L167
Or if HS https://github.com/hathach/tinyusb/blob/6ec5174d8b24d1f01a443c74a0a3dbee00523efc/hw/bsp/stm32h7/family.c#L195-L208

As suggested above, see if you can get one of the stock examples running first.

**Comment by gabrieltetar** [comment]
Thank you, using "portable/synopsys/dwc2" instead of "portable/st/synopsys" fixed the issue. It now works without the workaround
