### ISSUE TITLE
Please add .DS_store files to .gitignore

### ISSUE THREAD

**Issue by rppicomidi** [hathach/tinyusb#1448]
**Is your feature request related to a problem? Please describe.**
I just started using a Mac as a development platform for rp2040. I find .DS_Store files show up as untracked files. It would be too easy to commit them by accident.

**Describe the solution you'd like**
This Apple developer forum [discussion](https://developer.apple.com/forums/thread/30532) suggests to add the following to the .gitignore. I can create a pull request for this if you would like.
```
# macOS-specific files
.DS_Store
.Trashes
Thumbs.db
```

**Comment by hathach** [comment]
sure, please make an PR for this, I don't use mac to verify the change.

**Comment by hathach** [comment]
No problems at all, thanks for the update
