### ISSUE TITLE
dwc2 txfifo not cleared properly on close (dcd_dwc2.c @ 807)

### ISSUE THREAD

**Issue by Iktek** [hathach/tinyusb#1453]
### Operating System

Others

### Board

STM32L472 custom

### Firmware

Custom Firmware FreeRTOS, audio+cdc composite device

### What happened ?

On closing an endpoint the txfifo may not be flushed properly, which leads to no data transfered on a reopen.

### How to reproduce ?

- attach device to a host having 2 in endpoints configured
- close the 2 endpoints one after another
- on ep1 close grstctl TXFNUM is set to 0x1
- on ep2 close grstctl TXFNUM is set to 0x1 | 0x2 = 0x3 -> BUG
- txfifo of the even endpoint number is not flushed due to a wrong register value on dwc2->grstctl
- reopen endpoint does not make fifo writes possible as fifo is still full

### Debug Log as txt file

Issue is resolved by correctly writing the dwc2->grstctl register in line 811 of dwc2->grstctl
```diff
diff --git a/src/portable/synopsys/dwc2/dcd_dwc2.c b/src/portable/synopsys/dwc2/dcd_dwc2.c
index bb4d4042..63427fda 100644
--- a/src/portable/synopsys/dwc2/dcd_dwc2.c
+++ b/src/portable/synopsys/dwc2/dcd_dwc2.c
@@ -804,7 +804,7 @@ static void dcd_edpt_disable (uint8_t rhport, uint8_t ep_addr, bool stall)
     }
 
     // Flush the FIFO, and wait until we have confirmed it cleared.
-    dwc2->grstctl |= (epnum << GRSTCTL_TXFNUM_Pos);
+    dwc2->grstctl = (epnum << GRSTCTL_TXFNUM_Pos);
     dwc2->grstctl |= GRSTCTL_TXFFLSH;
     while ( (dwc2->grstctl & GRSTCTL_TXFFLSH_Msk) != 0 ) {}
   }
```

One could also implement it like (to be discussed):
`
 dwc2->grstctl = (dwc2->grstctl &~GRSTCTL_TXFNUM_Msk)  | (epnum << GRSTCTL_TXFNUM_Pos);
`
For my opinion it's completely ok to clear the whole grstctl because all bits (except the TXFNUM) are self-cleared.

**Comment by hathach** [comment]
fixed by #1454
