### ISSUE TITLE
Array out of bounds error

### ISSUE THREAD

**Issue by pigrew** [hathach/tinyusb#152]
dcd:437
``` 
   uint8_t const itf = tu_u16_low(p_request->wIndex);
uint8_t const drvid = _usbd_dev.itf2drv[itf];
```

This can access out of bounds memory if the host transmits a large value for wIndex.

Fixed in #150

**Comment by hathach** [comment]
Host shouldn't but we can't tell for sure. Yes, we should add TU_VERIFY before accessing the array. Thanks for spotting the issue.
