### ISSUE TITLE
USB HS Device Qualifier Descriptor  Callback

### ISSUE THREAD

**Issue by arilink** [hathach/tinyusb#1525]
### Operating System

Windows 10

### Board

STM32F407 USB HS+USB3300PHY

### Firmware

V1.3.0

### What happened ?

Does tingusb support STM32 f4+usb3300 high-speed devices? If yes, is there a device qualifier descriptor callback?

### How to reproduce ?

I have a new project that needs to use USB high-speed transmission, but it is found that high-speed devices need device qualification descriptors, but tinyusb does not find the corresponding callback function. How can I solve it?

**Comment by hathach** [comment]
not a bug
