### ISSUE TITLE
ESP32 audio microphone

### ISSUE THREAD

**Issue by LouisCARRIOU** [hathach/tinyusb#1527]
### Operating System

Windows 10

### Board

ESP32-S3

### Firmware

examples/device/audio_4_channel_mic

I also tried with the freertos like https://github.com/kaspernyhus/tinyusb/tree/audio_test_freertos/examples/device/audio_test_freertos

### What happened ?

usb device is well recognise, so I tried it and fill the i2s_dummy_buffer with rand() to make a white noise,  but

NO SOUND IS RECORDED onto the computer

I also tried with the tud_audio_write_support_ff , and the tud_audio_write directly  => Problem is the same 

### How to reproduce ?

in audio_4_channel_mic folder (or the audio_test_freertos)
make command
also tried with the idf.py -B_build/espressif_s3_devkitc -DFAMILY=esp32s3 -DBOARD=espressif_s3_devkitc -DIDF_TARGET=esp32s3 build

**Comment by PanRe** [comment]
Please try again once #1690 was merged! Thx!
