### ISSUE TITLE
CDC doesn't respect no flow control setting (DTR control needed to receive data)

### ISSUE THREAD

**Issue by MrGreensWorkshop** [hathach/tinyusb#1548]
### Operating System

Windows 10, Mac OS, I think in all OS es.

### Board

Raspberry pi pico

### Firmware

just simple app to test cdc behavior.

https://github.com/MrGreensWorkshop/RasPiPicoSDK_cdc_test

### What happened ?

When handshake is set to none, to receive data we need to enable DTR. We shouldn't be force to enable DTR to receive data. (other flow control status shouldn't be changed in cdc side if it is the case.)

I believe this is related with #872 maybe with #746 too.

please watch the gif file.

![raspi pico serial dtr](https://user-images.githubusercontent.com/76992231/177780477-e542724c-630b-4e83-a234-a48680f823a0.gif)

![CoolTermMac_term](https://user-images.githubusercontent.com/76992231/177949694-c8a83947-5dc3-46d0-8d29-4776fbe68a84.gif)

### How to reproduce ?

https://github.com/MrGreensWorkshop/RasPiPicoSDK_cdc_test

- Download
- Compile and run. (or just use binary named PicoTest.uf2)
- Connect to Raspberry pi pico to USB thats all. (No usb serial converters attached.)
- Use Terminal.exe or [CoolTerm](https://freeware.the-meiers.org/) or any other terminal let you set DTR.
- Check DTR behavior. 

### Expected behavior

This the demonstration that 2 FDTI USB serial converter connected each other with 3 pins.
```
Rx <- Tx
Tx -> Rx
GND <-> GND
```
It shouldn't be forced to enable DTR to receive data either sides. Please watch the gif file.

![usual usb serial](https://user-images.githubusercontent.com/76992231/177780995-f4d3242d-b360-488a-8ac6-d4a83e4ffb36.gif)

###  Cause

This happens when raspberry pi usb cdc is used.

This is other issue talks about same thing. 
https://github.com/hathach/tinyusb/discussions/932

Please check this file.

https://github.com/hathach/tinyusb/blob/master/src/class/cdc/cdc_device.c

it is checking DTR if it's on or not regardless checking flow control.
```
bool tud_cdc_n_connected(uint8_t itf)
{
  // DTR (bit 0) active  is considered as connected
  return tud_ready() && tu_bit_test(_cdcd_itf[itf].line_state, 0);
}
```

**Comment by TravisRo** [comment]
This has been done intentionally.  They use the DTR signal to detect when the PC/host has actually opened or closed the com port.  I agree, it causes problems it some cases.  Most of the arduino CDC implementations do this as well; it is fairly common.

I have a pull request submitted that adds a CH341 emulation class driver which would solve your problem.
[https://github.com/hathach/tinyusb/pull/1507](url)

You can get this from my fork here: [https://github.com/TravisRo/tinyusb/tree/master](url)

The api is nearly 100% compatible with the cdc driver except you have to change all of your "tud_cdc" prefixes to "tud_ch341"

**Comment by MrGreensWorkshop** [comment]
Thank you for responding my inquiry. Yes I checked the code. And Thank you for the PR #1507

When people use MCU which support USB, and if serial port is needed using CDC is common to use instead of using USB serial converters. When it happens, you expect using CDC to be the same as using a USB serial converter. Using DTR to detect connection shouldn't be implemented. We can't expect all application to raise DTR when open serial port. That's why I raise this issue.

**Comment by HiFiPhile** [comment]
@MrGreensWorkshop 
CDC class has very limited function. I made this issue long time ago https://github.com/hathach/tinyusb/issues/400 and had a long discussion https://github.com/hathach/tinyusb/pull/401

**Comment by MrGreensWorkshop** [comment]
I saw in #482 too. I think author of this repo only tested in VT100 terminals like PuTTY or Teraterm. That's why he thinks its ok, but it's not.

PuTTY or Teraterm terminals are made for VT100 etc., not exactly plain text transmission. You can use if you want. But those are uses other pins too. DTR -> DSR and DSR <- DTR. That's the problem. 

Asking host application for DSR on is reduce the compatibility with other apps if user is explicitly select no flow control.

**Comment by HiFiPhile** [comment]
I think you should ask pico SDK to remove tud_cdc_n_connected() test, just like #506 remove this test from examples.

**Comment by MrGreensWorkshop** [comment]
pico SDK -> They don't even understand the problem. Check this [#906](https://github.com/raspberrypi/pico-sdk/issues/906)

**Comment by MrGreensWorkshop** [comment]
I see your point.

**Comment by MrGreensWorkshop** [comment]
@hathach 
I see `examples/device/cdc_msc` not using `tud_cdc_n_available`, but example `examples/device/cdc_dual_ports` uses `tud_cdc_n_available`

This is how raspberry pi pico sdk implemented. they are using `tud_cdc_n_available` that's why its happening.
https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_stdio_usb/stdio_usb.c

**Comment by hathach** [comment]
> Kind of you are right it's their problem. I think there must be better implementation for tud_cdc_connected don't you think so?

Let me know if you figure out the better way to determine there is a connected client, I am happy to make the changes.

Note: there is a difference in cdc behavior when dtr is not set, the tx buffer will become overwritable, i.e if tx fifo is full, it will be overwritten. more details of this behavior is discussed in previous issue/pr mentioned above.

**Comment by MrGreensWorkshop** [comment]
I assume you are referring #482 ?

**Comment by MrGreensWorkshop** [comment]
I made some changes and test it's behavior.

https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_stdio_usb/stdio_usb.c

first changed this
```
bool stdio_usb_connected(void) {
    return true;
}
```
and renamed `tud_cdc_connected()` to `stdio_usb_connected()`

When port is opened all data in tx buffer output to terminal.
This is not problem because when handling data on pc we can flush buffer.

Is there any other concerns?

**Comment by hathach** [comment]
as mentioned above, the only difference in behavior is tx fifo can be overwritten when dtr is not set. When dtr is set, tinyusb will blocking wait for tx fifo to be sent since it is certain there is waiting client. In other words, If you send too many data in short period, there maybe some missing. 

connected() is option, going to support dtr or not is up to stdio integration i.e rpi team. For the changes you propose is within pico-sdk, you should ask them to see if it is acceptable or not.

**Comment by MrGreensWorkshop** [comment]
@hathach Things are more clear now. Thank you for your explanation.

**Comment by hathach** [comment]
no problem, I am glad that help. The current state of control signals (dtr,rts, cts etc...) in cdc acm are not standardized among terminal clients, though more and more terminal use dtr as connected nowsaday. I will try to revise/improve this later on when having time. I guess we could now close this issue here ?

**Comment by MrGreensWorkshop** [comment]
I open the [this PR](https://github.com/raspberrypi/pico-sdk/pull/932) on pico-SDK.

Clearly `tud_cdc_connected` used by choice of pico-sdk team.

> though more and more terminal use dtr as connected nowadays.

About that. It is also mentioned in #482.

> Universal Serial Bus Communications Class Subclass Specification for PSTN Devices for Abstract Control Model (ACM) ..

PSTN Devices are mostly modems. Most of time we need flow control to control data flow. Let's not confuse with modems.

The reason that I raise the issue is not about the terminals default settings. It's about the application side. Most people use terminals for test purpose. 

As you know more mcu have usb support nowadays, so serial port replace with CDC. People like me want to use cdc without any change in host application. Host serial app could be run on PC, mobile device or host mcu.

Thank you again for this great project.
