### ISSUE TITLE
Off by one error in Synopsys driver

### ISSUE THREAD

**Issue by pigrew** [hathach/tinyusb#156]
Issue found by Coverity:

dcd_synopsys.c:273:

```
  // Unsupported endpoint numbers/size.
  if((desc_edpt->wMaxPacketSize.size > 64) || (epnum > EP_MAX)) {
    return false;
  }

```

I believe this is an off-by-one, and it should be `epnum >= EP_MAX`.

However, I'd suggest using TU_ASSERT with the inverse logic:

```
TU_ASSERT((desc_edpt->wMaxPacketSize.size <= 64);
TU_ASSERT(epnum < EP_MAX);
```

This could also be made more clear by using names like `EP_COUNT` instead of `EP_MAX`.

**Comment by hathach** [comment]
I really like coverity scan now, I remembered register but struggled to get it running several years ago. This also remind me that I need to start writing some unit tests for the stack. The stack is aim to be Test-Driven Development (TDD), but heck, I never have time for such as fancy thing 😆😆

**Comment by pigrew** [comment]
Is it better for me to create pull requests for these simple things, or to just do the bug report?

**Comment by hathach** [comment]
It is much better if you could make an PR then fill in the information as above if it is a quick fix for you. Also you dont have to explain much, we all know if it is obvious issue. I actuall speak C better than English (non English speaker here) 😆😆
