### ISSUE TITLE
TinyUSB port for Arduino DUE SAM3X8E 

### ISSUE THREAD

**Issue by OptifySudarshanPatil** [hathach/tinyusb#1581]
TinyUSB is having great api for RNDIS. i used it with Raspberry PICO RP2040 earlier.
i wish i could find support for Arduino DUE SAM3X8E he will be great addidion as Arduino USB is limited to USB HID only.
And adding External Ethernet MAC (like W5500 for referance) to Arduino DUE SAM3X8E  is bit complicated because of certain library conflicts.

An simple TinySB port which will help to bring RNDIS feature to Arduino DUE SAM3X8E will be great for community.

Cheers!
sdrshnptl

**Comment by hathach** [comment]
unfortunately, I am short on time and won't be able to work on this anytime soon. Hopefully someone would make an PR for this.
