### ISSUE TITLE
HID class get HID descriptor request

### ISSUE THREAD

**Issue by pigrew** [hathach/tinyusb#168]
The HID class fails to reply when a request for the HID descriptor is made:

hid_device.c:208
```
    if (p_request->bRequest == TUSB_REQ_GET_DESCRIPTOR && desc_type == HID_DESC_TYPE_REPORT)
    {
      uint8_t const * desc_report = tud_hid_descriptor_report_cb();
      tud_control_xfer(rhport, p_request, (void*) desc_report, p_hid->reprot_desc_len);
    }
    else
    {
      return false; // stall unsupported request
    }
```

Based on the HID spec, it must also support HID_DESC_TYPE_HID.

This causes the HID checks in the USB validator to fail.

**Comment by hathach** [comment]
Thanks, I didn't know host will attempt to read this report as well. I should have run the compliance suite as you did, it is very helpful indeed :)
