### ISSUE TITLE
RP2040-Zero fails to show up as a USB device after disconnect

### ISSUE THREAD

**Issue by jthlim** [hathach/tinyusb#1730]
### Operating System

Others

### Board

RP2040-Zero

### Firmware

examples/device/hid_boot_interface

But really, every tinyusb example I tested exhibited the same problem. Even the pico-example hello_world/usb exhibits the same issues.

### What happened ?

On RP2040-Zero (by WaveShare), immediately after flashing the firmware, a TinyUSB device shows up and can interact with the computer.

However, upon disconnecting and reconnecting, the device no longer shows. Plugging it in to other devices also do not recognize the TinyUSB device.

Have noticed this with both RP2040-Zeros I own, and have seen this issue also on one of the Uni v4s -- a rp2040 based Steno Keyboard -- that I own (the other one works as expected).

Not reproducible on RPi Pico or WeAct Studio rp2040 boards -- disconnecting and reconnecting, or plugging them into other devices works as expected.

### How to reproduce ?

1. Build example/device/hid_boot_interface using github.com/raspberrypi/pico-examples
2. copy firmware to device
3. Observe device is working as expected
4. Unplug
5. Plug back in
6. Notice that device is not working, and that the device does not show up in system information.
7. Putting the device into bootrom mode, then using `picotool reboot` or re-copying the firmware will give a working USB until next disconnect.

This behavior has been seen with the host being Windows 10 or MacOS

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by jthlim** [comment]
@kilograham Tagging Graham as it seems he may have written some of this code.

Note: Bootloader shows reliably the USB device, and the original QMK firmware on the Steno keyboard works fine; just the tiny usb implementation only works after a reboot.

**Comment by jthlim** [comment]
Update: The rp2040 zero issues seem to be separate; the issue with tiny_usb devices not showing on the steno board persist though; and are intermittent.. most times it doesn't work; but when connecting to a sleeping machine, it seems to be able to wake it up *most* of the time, then work correctly after.

**Comment by jthlim** [comment]
Going to close this; ended up being a flash spi clkdiv issue.

**Comment by AlynxZhou** [comment]
> Update: The rp2040 zero issues seem to be separate (seems like they don't boot fullstop after disconnecting); the issue with tiny_usb devices not showing on the steno board persist though; and are intermittent.. most times it doesn't work; but when connecting to a sleeping machine, it seems to be able to wake it up _most_ of the time, then work correctly after.

I am sorry to bother you but I got the same problem with you, I have 3 RP2040-Zero from WaveShare, only 1 works, the other 2 cannot be detected by host after reconnecting, do you have workarounds for it? Thanks.

**Comment by AlynxZhou** [comment]
> Going to close this; ended up being a flash spi clkdiv issue.

OK, I find the reason and submit a fix to the pico-sdk: <https://github.com/raspberrypi/pico-sdk/pull/1421>.
