### ISSUE TITLE
Any plan to support STM32G0 series?

### ISSUE THREAD

**Issue by factoryal** [hathach/tinyusb#1748]
### Related area

new port support

### Hardware specification

STM32G0

### Is your feature request related to a problem?

no

### Describe the solution you'd like

Hi.

ST's Cortex-M0+ microcontroller G0 series has USB FS device and host controller on G0B and G0C.
It seems it only supports G4 series right now. Is there any plan to support STM32G0 series?

Thanks for checking this request.

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
question, please use discussion instead
