### ISSUE TITLE
Missing fields in audio_desc_input_terminal_t

### ISSUE THREAD

**Issue by s13n** [hathach/tinyusb#1782]
### Operating System

Linux

### Board

Raspberry Pi Pico

### Firmware

Raspberry Pi SDK - master branch, using TinyUSB 0.12.0

### What happened ?

A struct definition in header file src/class/audio/audio.h is missing two fields, compared to the definition in "USB Device Class Definition for Audio Devices Release 2.0".

See the definition of `audio_desc_input_terminal_t` starting in line 719 of file audio.h
Compare with table 4-9 in the USB document.

Missing fields are: `bTerminalID` and `iChannelNames`.

### How to reproduce ?

Read the mentioned source file and the USB document.

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
can you paste the link to the code in master branch, the 0.12.0 version is too old and line number may not be correct. Also please try to update tinyusb as well to see if it fixed recently.

**Comment by s13n** [comment]
The bug is still there in master, and the line in the file is still the same.

**Comment by pete-pjb** [comment]
Hi @hathach ,

I can add this to my PR if that is helpful - let me know...

Cheers,

Pete

**Comment by hathach** [comment]
@pete-pjb sure thing, if you already have the fix ready.

**Comment by hathach** [comment]
fixed by #1837
