### ISSUE TITLE
Building LwIP web server with CDC-NCM throws an error

### ISSUE THREAD

**Issue by ekawahyu** [hathach/tinyusb#1817]
### Operating System

MacOS

### Board

STM32F103C8T6 Blue Pill

### Firmware

examples/device/net_lwip_webserver

### What happened ?

Building LwIP web server example for STM32F103C8T6 Blue Pill with CDC-NCM stack throws an error

### How to reproduce ?

Steps to reproduce it:
1. Go to examples/device/net_lwip_webserver/src/tusb_config.h, and modify `CFG_TUD_ECM_RNDIS` to `1`
2. Go to examples/device/net_lwip_webserver and build: `make BOARD=stm32f103_bluepill all`

### Debug Log as txt file

```
(base) macos@Eka-MacBook-Pro net_lwip_webserver % make BOARD=stm32f103_bluepill all  
AS startup_stm32f103xb_asm.o
CC dcd_stm32_fsdev.o
CC system_stm32f1xx.o
.
.
.
CC ecm_rndis_device.o
CC ncm_device.o
/Users/macos/Developer/tinyusb/src/class/net/ncm_device.c: In function 'netd_control_xfer_cb':
/Users/macos/Developer/tinyusb/src/class/net/ncm_device.c:395:43: error: cast discards 'const' qualifier from pointer target type [-Werror=cast-qual]
  395 |         tud_control_xfer(rhport, request, (void*)&ntb_parameters, sizeof(ntb_parameters));
      |                                           ^
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
make: *** [../../rules.mk:131: _build/stm32f103_bluepill/obj/src/class/net/ncm_device.o] Error 1
```

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
the warning/error is fixed by #1819 however, you still couldn't compile with stm32f103 due to lack of SRAM. You may try to alter/hack some settings to save some ram
