### ISSUE TITLE
Unable to delete files via iOS 13

### ISSUE THREAD

**Issue by CollinCunningham** [hathach/tinyusb#182]
Hey @hathach - We ran into an issue using CircuitPython 5.0.0-alpha.4 with iOS & iPadOS 13. Limor mentioned this would be the best way to bring it to your attention.

**Describe the bug**
Unable to delete or overwrite files on Circuit Playground Express running CircuitPython 5.0.0-alpha.4. This functionality works with CircuitPython 4.1.0.

**Set up (please complete the following information):**
 - iOS 13 & iPadOS 13.1
 - Circuit Playground Express
 - CircuitPython 5.0.0-alpha.4

**To Reproduce**
1. Connect CPX to iPhone or iPad via Lightning adapter or USB-C (iPad Pro)
2. Open Files app
3. Navigate to CIRCUITPY drive
4. Attempt to delete or replace code.py
(code.py may disappear, but reappears when navigating back and then reopening CIRCUITPY)

**Expected behavior**
Pasting a new version of code.py in CIRCUITPY should replace old version, prompting CPX to restart and run the new code.

**Screenshots**
https://www.dropbox.com/s/k99r1x7bjuck86r/ios13-cirpy5-a4.mov?dl=0

**Additional context**
The process we've successfully used with CircuitPython 4.1.0  & iOS 13 can be found here:
https://blog.adafruit.com/2019/09/19/program-circuitpython-devices-with-iphone-ios-13/

Let me know if I can provide any more info. Thanks!

**Comment by hathach** [comment]
thanks @CollinCunningham it is as details as it can go, I will order an lighting-to-usb adapter to test with.

**Comment by hathach** [comment]
@CollinCunningham I just tested CPX with current master, its seems to work with my IPX on iOS 13.1 . I could be able to remove files from CPX

**Comment by CollinCunningham** [comment]
You're able to delete files from CPX using the Files app?  Strange.

**Comment by hathach** [comment]
I will do more tests later on, It should be the same for iPhone 10 and 11. It is mostly the driver which is the same on both phones. Maybe I get lucky, will get you update with further testing.

**Comment by CollinCunningham** [comment]
Just for reference, pasting this from our email thread

> I just loaded that new uf2 up and tested on iPad Pro (iPadOS 13.1) and was unable to delete files from CPX.
> I then updated to iPadOS 13.1.2 and had the same issue.
> 
> I’ve been loading the uf2 files onto CPX from macOS. Just in case it’s helpful - here’s a comparison between files seen on CPX running the new uf2 versus the CPX running 4.1.0 (which is working):

![image](https://user-images.githubusercontent.com/1213906/66070305-0f014880-e51f-11e9-8ffa-e5c646606855.png)

[...]

> Also - as an experiment, I connected CPX running new uf2(5.0.0-alpha.4-99) to a Windows 10 machine and deleted these files:
> ._boot_out.txt
> ._code.py
> .fseventsd
> .metadata_never_index
> .Trashes
> 
> I then connected the CPX to iPad Pro and was able to delete and replace files successfully.

**Comment by hathach** [comment]
Another person also confirms that removing those hidden files help as well. It probably has something to do with the filesystem contents as well. 

Here is the disk image of the cpx before removing hidden files for reproduction https://www.dropbox.com/s/t3rdc0qchxsqtxb/CIRCUITPY.dmg?dl=0

**Comment by hathach** [comment]
@CollinCunningham interesting note that copying all files from the dmg file to SD card. And yeah, iOS couldn't removes file on SD card. I guess it is possibly iOS bug ?!?!

**Comment by CollinCunningham** [comment]
@hathach Possible the `.metadata_never_index` file is incompatible with iOS?

**Comment by hathach** [comment]
@CollinCunningham after tons of trial and erorrs, I finally could determine the root causes of the issue. The present of file `.Trashes` will prevent the iOS from doing any delete operation. This file present is kind of weird, it should be a **Directory** not file. I have no idea how it appear in the CPX in the first place, but not creating it will help 

![image](https://user-images.githubusercontent.com/249515/66195882-c766f200-e6c1-11e9-8dca-4237e555e56d.png)

**Comment by dhalbert** [comment]
That is a CircuitPython bug and I've filed an issue about that: https://github.com/adafruit/circuitpython/issues/2199. It's easy to fix.

**Comment by dhalbert** [comment]
OK, it's more complicated. We deliberately made `.Trashes` a file, not a directory, because for MacOS, that prevents a "trash can" from being created on the filesystem with deleted files. It works to do that on MacOS, but apparently iOS is not acting properly. So we could report this to Apple.

**Comment by hathach** [comment]
Thanks @dhalbert for clear thing up. It makes more sense now :)

**Comment by hathach** [comment]
since it isn't usb issues. @CollinCunningham @dhalbert Let's me know if we could now close this issue here.

**Comment by CollinCunningham** [comment]
Cool - we'll relay the bug to apple. Thanks all for the detective work!
