### ISSUE TITLE
bit field arrangement is not guaranteed by the C standard (cdc.h)

### ISSUE THREAD

**Issue by jefftrull** [hathach/tinyusb#1892]
### Operating System

Linux

### Board

n/a

### Firmware

examples/device/cdc_msc

### What happened ?

Compilation under sdcc (4.0 and 4.2) fails on [the assert at line 410 of cdc.h](https://github.com/hathach/tinyusb/blob/86c416d4c0fb38432460b3e11b08b9de76941bf5/src/class/cdc/cdc.h#L410) which checks the size of `cdc_line_control_state_t`. The exact layout of bitfields is apparently implementation-defined and sdcc makes a different choice than gcc in this case. See [the SDCC discussion](https://sourceforge.net/p/sdcc/bugs/3530/) for more info. So this seems to be a kind of C standard conformance issue.

There is a straightforward workaround which I will supply in a PR.

### How to reproduce ?

Build tinyusb under sdcc for 8051, for example by using [my branch](https://github.com/jefftrull/tinyusb/tree/mcs51). Change src/class/cdc/cdc.h to match master and observe this error message:

`src/class/cdc/cdc.h:410: warning 215: static assertion failed: "size is not correct"`

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by jefftrull** [comment]
sdcc also rejects bitfields larger than 16 bits; the PR will cover that as well

**Comment by hathach** [comment]
can you specify which board/mcu you are using, if possible please add an PR to include the mcu into board support, so that we could include the SDCC into ci build to fix any future changes.

**Comment by jefftrull** [comment]
This will eventually be for the (obsolete) ALi M5623 in certain Canon scanners; I am in the process of porting to SDCC but am facing code size issues that require significant changes to the TinyUSB core so a PR is somewhat in the future.

**Comment by hathach** [comment]
thank you for the info, indeed the code size has been increased quite a bit lately due to lots of added features. Maybe in the future we should have some option to trim down the code size e.g no dynamic configuration etc..
