### ISSUE TITLE
tud_midi_n_stream_write() always writes system messages to cable 0

### ISSUE THREAD

**Issue by rppicomidi** [hathach/tinyusb#1909]
### Operating System

Others

### Board

Raspberry Pi Pico

### Firmware

https://github.com/rppicomidi/pico-usb-midi-processor

### What happened ?

I am developing a new processor class for my project. When I call tud_midi_n_stream_write() to write a system exclusive message to cable 1 instead of cable 0, the message is sent to cable 0.

### How to reproduce ?

You can see by inspection of the [code](https://github.com/hathach/tinyusb/blob/master/src/class/midi/midi_device.c) near lines 290-310 that packets for system messages do not have cable_num << 4 OR'd to the first byte. Also lines 264, 268, 330, and 333 should depend on cable_num or have the cable number field masked. @hathach I can submit a pull request for this if you would like.

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
sure please submit a PR if possible.
