### ISSUE TITLE
`remove_volatile_cast()` not available in src/portable/raspberrypi/rp2040/dcd_rp2040.c

### ISSUE THREAD

**Issue by dhalbert** [hathach/tinyusb#1944]
### Operating System

Linux

### Board

RP2040

### Firmware

latest `master`, as of today

### What happened ?

I'm bringing CircuitPython's use of tinyusb up to date. We were about a year behind. I'm getting a compile error here because the macro `remove_volatile_cast()` is not defined here:
https://github.com/hathach/tinyusb/blob/990fb6ae5c4d9d4b77c5a9ecb3a2abe899dd2712/src/portable/raspberrypi/rp2040/dcd_rp2040.c#L300
It is defined in `pico-sdk/src/rp2_common/hardware_sync/include/hardware/sync.h`, but there doesn't seem to be an `#include hardware/sync.h` directly or indirectly done in `dcd_rp2040.c`.

See sample compile failure here:
https://github.com/adafruit/circuitpython/actions/runs/4379438712/jobs/7665918999#step:10:28

circuitpython PR is https://github.com/adafruit/circuitpython/pull/7702

### How to reproduce ?

see above

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
have you tried to bump up pico-sdk ? this cast is added recently by rpi team, and actually pass tinyusb ci.

**Comment by dhalbert** [comment]
Yes, I am running with pico-sdk 1.5.0. `remove_volatile_cast()` is there, it's just that the .h file that defines it is not being included directly or indirectly by `dcd_rp2040.c`.

**Comment by dhalbert** [comment]
I am thinking that `#include hardware/sync.h` should explicitly be in `dcd_rp2040.c`.

**Comment by kilograham** [comment]
yes it probably should;

I assume this is failing because you aren't using OSAL_PICO

**Comment by dhalbert** [comment]
> I assume this is failing because you aren't using OSAL_PICO

That's true. Maybe we should look at using osal across our multiple ports.
