### ISSUE TITLE
Port STM32 Highspeed core

### ISSUE THREAD

**Issue by hathach** [hathach/tinyusb#198]
**Description**
It is more likely a test than port, probably adjusting base address etc to get the OTG HS core work with the stack. Need to find an dev kit that support OTG HS connection.

board with OTG HS connection 
- [x] STM32F723E Discovery with builtin HS PHY
- [x] STM32F769I Discovery require external PHY for OTG HS
- [x] STM32H743Eval with external PHY for OTG HS

**Comment by hathach** [comment]
2 STM32F7 board with OTG HS connection are on order 
- STM32F723E Discovery with builtin HS PHY
- STM32F769I Discovery require external PHY for OTG HS

**Comment by pigrew** [comment]
The new $10 st-link mini v3 have a STM32F7 and would be a nice target platform, too.

**Comment by hathach** [comment]
> The new US$10 st-link mini v3 have a STM32F7 and would be a nice target platform, too. The board uses the integrated PHY and has USB ESD protection. One would need to solder on a few pins for JTAG to the board, though.

That is a very good tips, though I already bought those boards. It is still nice to get up with a known good board, running chip vendor stock example to verify hw work etc.. and I don't have much love with soldering as well :). I am sure others will find it useful.

**Comment by UweBonnes** [comment]
Any news on STM32 USB-HS? Modding the StlinkV3 for blackmagic would be a nice target.

**Comment by UweBonnes** [comment]
Even having the StlinkV3 HS USB only work as FS would be a big plus.

**Comment by hathach** [comment]
@UweBonnes I don't have stlink V3 to test with ( I wished you remind me earlier since I just placed an order from Digikey last week for esp32s2). Good news is the stm32 hs is working well with stm32h743eval if you happen to have the board https://github.com/hathach/tinyusb/tree/add-stm-hs . It still needs a bit more testing though. 

Meanwhile if you have the board would you mind adding an BSP for it,  It doesn't need to have running USB just yet, just have the `board_test` example is a good start ( it ensure we correct set clock and have gpio running). The example will blink at 1000 ms normally and blink at 250 ms when button is pressed. Afterwards, I could try to add some USB specific code and we can see if  that could get USB running on stlinkv3  

PS: I am currently tied with esp32s2 work,thing will be rather slow.
