### ISSUE TITLE
passive disconnection detection

### ISSUE THREAD

**Issue by mcl-uk** [hathach/tinyusb#1980]
### Related area

device stack

### Hardware specification

rp2040 pico-w

### Is your feature request related to a problem?

I have an odd-ball usb-host msc application using this SD-card to usb cable: https://www.spypoint.com/en/products/cell-link-cable/cl-cbl . I'm plugging the usb end into a pico-w and the SD card end into a camera. When the camera is off or idle you can access the SD card memory via the usb as a regular usb mass storage device from the pico. But when the camera becomes active the usb interface is disabled - the SD card end has priority. Unfortunately the magic cable does not drop the usb bus when it becomes disabled, it merely stops responding to usb requests. Consequently tinyUSB does not see this as an un-mount and just locks up - although somehow not until re-connection. I dont get a umount callback.   

### Describe the solution you'd like

Ideally the stack would interpret the lack of response an an un-mount whithout _requiring_ the bus to drop.
Thanks so much for your time.

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
unmount requires a physical bus signal (SE0), if there is no bus signal change -> no event. Anyway to do it differently is only asking for troubles. If your media is not available, detect and response correctly with scsi command e.g ejected media.
