### ISSUE TITLE
USB3.0 (xHCI) driver support

### ISSUE THREAD

**Issue by 31kothari** [hathach/tinyusb#2]
Hi,

May I know by what time, xHCI driver will be available in tinyUSB?

Thanks for your code and looking for xHCI driver support for Bare Metal.

Thanks!

**Comment by kaushalmp** [comment]
Any updated in this request ?
is there a plan to support xhci in nearest future ?

**Comment by zhugengyu** [comment]
Hello, we may try this https://github.com/sakumisu/CherryUSB/tree/master/port/xhci first, then consider merge to tinyUSB,  since it's all for MCU/SoC  @hathach @31kothari @kaushalmp

**Comment by zhugengyu** [comment]
I have try xhci on CherryUSB for a while, function like mouse/keyboard/mass-storage are okay, but have some touble handling hub, I have little experience on Hub, if some one handles help ...
