### ISSUE TITLE
function tud_descriptor_configuration_cb  parameter index is not used 

### ISSUE THREAD

**Issue by epowsal** [hathach/tinyusb#2014]
### Operating System

Windows 11

### Board

esp32 s3

### Firmware

default

### What happened ?

null action

### How to reproduce ?

no

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

no

### Screenshots

origin code:

uint8_t const *tud_descriptor_configuration_cb(uint8_t index)
{
    (void)index; // for multiple configurations
    return (uint8_t const*)EspTinyUSB::descriptor_config_if;
}

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
There is no issue with this at all
