### ISSUE TITLE
(Possible bug) HID state event lag observed when timer task is not used to spam "tud_hid_report" updates

### ISSUE THREAD

**Issue by noisysoil** [hathach/tinyusb#2020]
### Operating System

Linux

### Board

Pico 2040, ESP32-C3 and ESP32-S3

### Firmware

Pico SDK 1.5.0 with default TinyUSB submodules.
Espressiv SDK 11.2.0 with default TinyUSB submodules.

### What happened ?

Correct me if I'm doing something wrong, but here's what I'm observing when trying to use the least power on the USB device by not doing uneccessary operations, such as spamming a HID report when not needed:

I have a gamepad device report mechanism based on the TinyUSB examples.

- On device interrupt -> `tud_hid_ready`? -> `tud_hid_report`.
- (Optional, works without the issue) Timer task (every poll interval, set to 4ms) -> `tud_hid_ready`? -> `tud_hid_report`.
-- Timer task also calls `tud_task`.

However, my host's `tud_hid_set_idle_cb` `Rate Ms` reponse reports `0`; TinyUSB comments for this function state the value means as follows:
```
// Invoked when received SET_IDLE request. return false will stall the request
// - Idle Rate = 0 : only send report if there is changes, i.e skip duplication
// - Idle Rate > 0 : skip duplication, but send at least 1 report every idle rate (in unit of 4 ms).
```
Thus my host reports it prefers `Idle Rate` = `0` -> only update if there are changes.

Thus I removed `tud_hid_ready`? -> `tud_hid_report` from the timer task - and _only_ send HID reports when an interrupt from a button / GPIO on the USB device is triggered.

This works for most use cases, but in the case (_outlined in 'How to reproduce'_) previous HID updates are lost when the host HID app is not running, unless the timer task spams `tud_hid_ready`? -> `tud_hid_report`.

### How to reproduce ?

Use one of the TinyUSB gamepad / Joystick examples which includes a timer that calls `tud_hid_report` - which is disabled for this test.
The USB device should have a trigger (e.g. button) to invoke an event that will send a HID gamepad / joystick report on state change - e.g. gamepad HAT up and down on interrupt GPIO HIGH and LOW, or a similar mechanism.

- [CODE] Comment out the timer's call to `tud_hid_report`.
- [HOST] Run a HID test app - in the case of Linux, `jstest-gtk` or similar.
- [USB DEVICE] Test the button / up / down and observe the reponses in the [HOST] HID app, which should correctly reflect the HID button state sent by the USB device.
- [USB DEVICE] _Keep holding the button down_ on the USB device.
- [HOST] Quit the joystick test app.
- [USB DEVICE] Release the previously held button.
- - At this stage, `tud_hid_ready` reports as available and the HID report is sent.
- [HOST] Run the HID test app.

Result: The HID test app reveals that the last action from the USB device did not update the host's HID state - e.g. the button report should be the released / 'up' state.  Instead it reports the held / 'down' state.

If the timer task calls `tud_hid_report` periodically, then this won't happen.

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

I can't access the logs in my configuration (one device, using CDC as internal debug output) but from reports it looks like there's a 'lag' of one event in the report when the  state of `tud_hid_ready` changes.

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
> [HOST] Quit the joystick test app.
> [HOST] Run the HID test app.

There is nothing tinyusb lib can do to fix this scenario, the report is delivered to PC host. Host decides not to forward past event to test app or test app simply does not query those events is out of each for a usb device. You can mix both approach by having an periodic timer with reasonably large enough timer
