### ISSUE TITLE
Support for Silabs' efr32fg25

### ISSUE THREAD

**Issue by ChipopoLM** [hathach/tinyusb#2056]
### Related area

New port support

### Hardware specification

efr32fg25

### Is your feature request related to a problem?

Silicon Labs released their new Flex Gecko, efr32fg25. It is the first Flex Gecko with a USB peripheral.

### Describe the solution you'd like

I would like to be able to work with the TinyUSB stack over the efr32fg25 device.

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
if the mcu use dwc2 controller like other gecko chip, most of the work is already done. You only need to minor mcu driver and bsp to get it running. Unfortunately I don't have any board with this mcu and have no plan to buy one, unless it is like sub 10$
