### ISSUE TITLE
Usb host wifi high speed

### ISSUE THREAD

**Issue by JPB1JPB1** [hathach/tinyusb#2147]
### Related area

Teensy 4.1

### Hardware specification

Imxrt

### Is your feature request related to a problem?

Example of usb host high speed support for one wifi dongle..
Thanks

### Describe the solution you'd like

Example code with reference 

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
this is host rndis, unfortunately, I don't have an plan/time to add support this. PR is welcome
