### ISSUE TITLE
What does `_xact` stand for?

### ISSUE THREAD

**Issue by rajivr** [hathach/tinyusb#216]
In `usbd_control.c`, I noticed API with signature ending with `_xact`. I was wondering what `xact` stood for in tinyusb code base?

**Comment by hathach** [comment]
it stands for transaction, `xfer` = multiple `xact`

**Comment by rajivr** [comment]
As always, thanks for the quick reply. @hathach :-)

**Comment by hathach** [comment]
I am happy to help :)
