### ISSUE TITLE
eptri clears wrong endpoint

### ISSUE THREAD

**Issue by xobs** [hathach/tinyusb#218]
At https://github.com/hathach/tinyusb/blob/master/src/portable/valentyusb/eptri/dcd_eptri.c#L418, opening an OUT endpoint will also clear any pending buffer for the IN endpoint.  The line should read:

```c
    else if (ep_dir == TUSB_DIR_IN) {
```

**Comment by hathach** [comment]
yeah, would you mind submit PR to fix this :)

**Comment by hathach** [comment]
Fixed by #219
