### ISSUE TITLE
audio_4_channel_mic on STM32F411 with modified tud_audio_tx_done_post_load_cb

### ISSUE THREAD

**Issue by klaus-liebler** [hathach/tinyusb#2256]
### Operating System

Windows 11

### Board

BlackPill F411

### Firmware

audio_4_channel_mic example (unmodified and modified, see below)

### What happened ?

I successfully integrated the audio_4_channel_mic example in a new STM32CubeIDE project and used "plot_audio_samples.py" to test it. When I looked at the plot, I saw that the value 1 remains constant for two samples (see marking in the screenshot below). According to the source code, the value 1 should only be displayed for one sample.
<img width="541" alt="image" src="https://github.com/hathach/tinyusb/assets/7479349/81517935-6093-403d-985e-5cf049cb5b2a">

I investigated further and changed the "Generate dummy data" code  to get unique sample values on all four channels 
```C
for(int i=0;i<48;i++){
  i2s_dummy_buffer[0][2*i]   = 100+i;
  i2s_dummy_buffer[0][2*i+1] = 200+i;
  i2s_dummy_buffer[1][2*i]   = 300+i;
  i2s_dummy_buffer[1][2*i+1] = 400+i;
}
```

Again I started "plot_audio_samples.py". 

Expected result: A sawtooth with continuously increasing values from 400->447

Actual result: A sawtooth with the values 400->446 and then a drop to 100 (47 of 48 values of second fifo, second channel, then the first value oder first fifo and first channel).

<img width="582" alt="image" src="https://github.com/hathach/tinyusb/assets/7479349/bb905196-ecf7-41c4-afca-f7931d03b21e">

### How to reproduce ?

Compile and run example here [https://github.com/klaus-liebler/soundcard](https://github.com/klaus-liebler/soundcard)

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

Not available

### Screenshots

See above

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by HiFiPhile** [comment]
Could you try #2259 ?

After fix:
![image](https://github.com/hathach/tinyusb/assets/4375114/524edbaf-b1a2-4b3a-b099-4031b6f28b7d)

**Comment by klaus-liebler** [comment]
Thank you so much, @HiFiPhile . I can confirm, that #2259 fixes the problem.

Regards, Klaus
