### ISSUE TITLE
Adding contributor information to readme or seperate contributors file

### ISSUE THREAD

**Issue by PTS93** [hathach/tinyusb#226]
Given that TinyUSB is getting a lot of traction and a lot more ports are coming in. Maybe its a good idea to name all the people who did work for specific ports?
The readme or a contributors file sound like a good idea. I think that would be rather valuable for the future if you want to contact specific people for certain ports.

**Comment by hathach** [comment]
@PTS93 Yeah, you are absolutely right. I should have done this earlier. I am sure the list will grow lengthy in the future, so I think it is best to put people with their work on separated files, and have thanks note & link to that from readme. Thank you very much for reminding :)

**Comment by hathach** [comment]
@PTS93 just go through the overall development and add this in https://github.com/hathach/tinyusb/pull/227 . Let's me know if it looks OK :)

**Comment by PTS93** [comment]
Looks great!
(Very kind of you to include me, I didn't expect that for just an example)

**Comment by hathach** [comment]
@PTS93 I tried my best to include everyone involved :)
