### ISSUE TITLE
"Conding" typos

### ISSUE THREAD

**Issue by lurch** [hathach/tinyusb#2330]
### Operating System

Linux

### Board

All

### Firmware

n/a

### What happened ?

There's a [few places](https://github.com/search?q=repo%3Ahathach%2Ftinyusb%20conding&type=code) where the word "conding" has been used, which I assume is a typo for "coding"?
Obviously for backwards-compatibility the existing misnamed constants need to be kept, but I wonder if it'd be possible to use some `#define`s or something to also add correctly-spelt versions of the constants?

### How to reproduce ?

n/a

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

n/a

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
fixed, thank you for spotting the issue. I made quite a bit of typos in early days.
