### ISSUE TITLE
An new example of Rdnis + CDC

### ISSUE THREAD

**Issue by sidd-kishan** [hathach/tinyusb#2345]
### Related area

USB wifi dongle

### Hardware specification

rp2040

### Is your feature request related to a problem?

I have built a project to use Pi Pico W as a usb wifi dongle over RDNIS https://github.com/sidd-kishan/pico-webserver using the lwip example but I need a way to set wifi creds dynamically with cdc port 

### Describe the solution you'd like

There should be an example to demonstrate RDNIS to run with a cdc port.

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by HiFiPhile** [comment]
You can compare [cdc_uac2](https://github.com/hathach/tinyusb/tree/master/examples/device/cdc_uac2) and [uac2_headset](https://github.com/hathach/tinyusb/tree/master/examples/device/uac2_headset) example to learn how composite device works, especially `usb_descriptors.c` and `tusb_config.h`

It's impossible to maintain composite device examples of all combinations.
