### ISSUE TITLE
sam.h missing

### ISSUE THREAD

**Issue by cyber-murmel** [hathach/tinyusb#2418]
### Operating System

Linux

### Board

qtpy

### Firmware

examples/device/cdc_msc

### What happened ?

When trying to compile the cdc_msc example for QTPy, the compilation stops with the error
```
/tmp/tinyusb/src/portable/microchip/samd/dcd_samd.c:34:10: fatal error: sam.h: No such file or directory
   34 | #include "sam.h"
```

The solution outline in #616 isn't applicable.

### How to reproduce ?

```shell
git clone git@github.com:hathach/tinyusb.git
cd tinyusb/examples/device/cdc_msc
BOARD=qtpy make
```

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

```
CC dcd_samd.o
/tmp/tinyusb/src/portable/microchip/samd/dcd_samd.c:34:10: fatal error: sam.h: No such file or directory
   34 | #include "sam.h"
      |          ^~~~~~~
compilation terminated.
make: *** [/tmp/tinyusb/examples/build_system/make/toolchain/arm_gcc_rules.mk:52: _build/qtpy/obj/src/portable/microchip/samd/dcd_samd.o] Error 1
```

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
please read getting started guide
