### ISSUE TITLE
kinetis frdmk32l2a4 device examples fail to enumerate / don't work (FIX AVAILABLE)

### ISSUE THREAD

**Issue by karlp** [hathach/tinyusb#2464]
### Operating System

Linux

### Board

frdmk32l2a4

### Firmware

examples/device/cdc_msc

### What happened ?

The clock config file used is wrong.  I'm not sure how it ever worked, but perhaps the defaults used to be different.
The board makefile here: https://github.com/hathach/tinyusb/blob/master/hw/bsp/kinetis_k32l2/boards/frdm_k32l2a4s/board.mk#L11 is including the "project_template" clock_config.c file for the _device_ "K32L2A4S" which is here: https://github.com/hathach/mcux-sdk/blob/main/devices/K32L2A41A/project_template/clock_config.c#L179  
Compare this with the _board_ default clock_config here: https://github.com/hathach/mcux-sdk/blob/main/boards/frdmk32l2a4s/clock_config.c#L211

The FIRC div1 output is _disabled_ but it must be enabled (div1) for firc to be used as the usb 48MHz clock.

There are multiple options to fix this, so I'm not sure what your desired path is.

a) use the _board_ project template from mcux.  (This requires adding SMC peripheral support, because it runs at 96Mhz)
b) use the _board_ "default" from mcux  (This works, and is "simple")
c) Move clock_config.c into the tinyusb BSP for the board

### How to reproduce ?

1. make BOARD=frdm_k32l2a4s DEBUG=1 LOGGER=rtt  LOG=2 V=1 clean all
2. flash
3. plug in device

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

not really relevant, as soon as the proper clock is turned on, everything works properly as expected.

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by karlp** [comment]
```
diff --git a/hw/bsp/kinetis_k32l2/boards/frdm_k32l2a4s/board.mk b/hw/bsp/kinetis_k32l2/boards/frdm_k32l2a4s/board.mk
index f69700139..851968794 100644
--- a/hw/bsp/kinetis_k32l2/boards/frdm_k32l2a4s/board.mk
+++ b/hw/bsp/kinetis_k32l2/boards/frdm_k32l2a4s/board.mk
@@ -8,8 +8,8 @@ CFLAGS += -Wno-error=unused-parameter -Wno-error=redundant-decls -Wno-error=cast
 # All source paths should be relative to the top level.
 LD_FILE = $(MCU_DIR)/gcc/K32L2A41xxxxA_flash.ld
 
-SRC_C += \
-       $(MCU_DIR)/project_template/clock_config.c \
+#SRC_C += $(SDK_DIR)/boards/frdmk32l2a4s/project_template/clock_config.c  # this needs SMC, and runs at 96Mhz...
+SRC_C += $(SDK_DIR)/boards/frdmk32l2a4s/clock_config.c
 
 # For flash-jlink target
 JLINK_DEVICE = K32L2A41xxxxA
```

Is a sufficient fix, option "B" from above.

**Comment by hathach** [comment]
I made an PR based on option C, though I don't have the board to test with, please test it out to see if that works now. Thank you

**Comment by karlp** [comment]
Confirmed that it works.  I cherry-picked my WIP to enable host mode and it works too.

**Comment by hathach** [comment]
> Confirmed that it works. I cherry-picked my WIP to enable host mode and it works too.

thank you, it is merged now :)
