### ISSUE TITLE
USB Audio Mic is unusable if tud_task isn't called thousand times a second (missed packets?)

### ISSUE THREAD

**Issue by Kilklang26** [hathach/tinyusb#2485]
### Operating System

Windows 10

### Board

STM32F4

### Firmware

custom firmware

### What happened ?

Audio Mic works with the base example where the MCU does nothing but calling tud_task. However, any real use case involves other tasks processed by the MCU. Any processing that takes too long without calling tud_task (haven't checked exactly, but seems close to a millisecond or a few hundred us), and the received audio data on the computer is corrupted (zeros in place of the real audio data).
Like if TinyUSB wasn't buffering requests from the host, and missing or discarding them.

### How to reproduce ?

Use the Audio Mic 1 channel demo
Add a random time wasting code in the main loop like a for loop with volatile int
See the audio data getting glitchier and glitchier as the loop time duration increases

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

Cannot provide debug info

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by HiFiPhile** [comment]
There are already many discussions regarding real time data streaming, basically 2 options:

- It's user's responsibility to make your code running in a non blocking way, eg. no `Delay()`.
- Put `tud_task()` inside USB ISR, eg. `OTG_FS_IRQHandler()`.
