### ISSUE TITLE
Unexpected  ReportID

### ISSUE THREAD

**Issue by GitHobi** [hathach/tinyusb#2491]
### Operating System

Linux

### Board

ESP32-S3-DevKit-1

### Firmware

n/a

### What happened ?

I'm trying to implement a FIDO2 USB Device. Using espressif-tinyUsb within Arudino IDE. Adapted standard CustomHIDDevice - just exchanged the report_descriptior with a FIDO2 compliant one - see attachment. 
[fido.txt](https://github.com/hathach/tinyusb/files/14394079/fido.txt)
Communication is comming in using requestID 255 - which is not "visible" within the scatch and does not match the specified one. 

### How to reproduce ?

Compile the attached scatch. 
Go e.g. to  "https://webauthn.io"
Select "register"
You shoud see the follwing log message:

entry 0x403c98d0
[    97][D][esp32-hal-tinyusb.c:680] tinyusb_enable_interface(): Interface HID enabled
[    97][I][sketch_feb24a.ino:37] CustomHIDDevice(): [sketch_feb24a.ino] 
[   100][D][USBHID.cpp:61] tinyusb_enable_hid_device(): Device[0] len: 34
[   341][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled

[   847][I][sketch_feb24a.ino:46] begin(): [sketch_feb24a.ino] 
[   848][D][esp32-hal-tinyusb.c:569] tinyusb_load_enabled_interfaces(): Load Done: if_num: 1, descr_len: 41, if_mask: 0x4
[   853][I][sketch_feb24a.ino:102] setup(): [sketch_feb24a.ino] ready to go!
[   859][I][sketch_feb24a.ino:74] vendorEventCallback(): [sketch_feb24a.ino] 
[  1437][I][sketch_feb24a.ino:74] vendorEventCallback(): [sketch_feb24a.ino] 
[  1438][V][USBHID.cpp:245] tud_hid_set_idle_cb(): instance: 0, idle_rate:0
[  1440][V][USBHID.cpp:224] tud_hid_descriptor_report_cb(): instance: 0
[  1447][D][USBHID.cpp:176] tinyusb_load_enabled_hid_devices(): Loaded HID Desriptor with the following reports:
[  1456][D][USBHID.cpp:184] tinyusb_load_enabled_hid_devices():   ID:   1, Type:   INPUT, Size: 32, Usage:   VENDOR
[  1466][D][USBHID.cpp:184] tinyusb_load_enabled_hid_devices():   ID:   1, Type:  OUTPUT, Size: 32, Usage:   VENDOR
[  7387][D][USBHID.cpp:269] tud_hid_set_report_cb(): instance: 0, report_id: 255, report_type: OUTPUT, bufsize: 31

As we can see, there is a set_report for report_id 255 ... which is unexpected, as we registered our device for resport_id 1. 

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

see above

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by HiFiPhile** [comment]
Please report it to Arduino, USBHID.cpp is not a part of tinyUSB.
