### ISSUE TITLE
Can Add support portable stm32h7 in src/portable/st/stm32_fsdev/dcd_stm32_fsdev.c

### ISSUE THREAD

**Issue by chunyiou** [hathach/tinyusb#2677]
### Related area

src/portable/st/stm32_fsdev/dcd_stm32_fsdev.c

### Hardware specification

stm32h7

### Is your feature request related to a problem?

Used tinyUSB on the STM32H7 platform

### Describe the solution you'd like

Used tinyUSB on the STM32H7 platform

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
H7 is already supported with dwc2
