### ISSUE TITLE
The cdc_msc example did not run with CDC UART feature normally on board LPCXpresso55S69 & LPCXpresso54114

### ISSUE THREAD

**Issue by suyongyq** [hathach/tinyusb#277]
Describe the bug

The cdc_msc example did not run with CDC UART feature normally. When I buidl & download the image, the MSC device can display in my PC. the CDC UART can be recognized as well. But the CDC UART in terminal software (tera term) did not echo anything like I tried with a STM32F103 board.

Set up (please complete the following information):

    OS: Windows 7 & Ubuntu 18.4 LTS
    Board: LPCXpresso55S69 & LPCXpresso54114
    Firmware Code: examples/device/cdc_msc

**Comment by hathach** [comment]
#117 #113

**Comment by hathach** [comment]
should be fixed by #808 and #811
