### ISSUE TITLE
HID KEYBOARD BUG

### ISSUE THREAD

**Issue by 0cococ** [hathach/tinyusb#2802]
### Operating System

Windows 11

### Board

ESP32S3

### Firmware

I use the same code on the computer and it can output A normally, but there is no response on Android.

### What happened ?

I use the same code on the computer and it can output A normally, but there is no response on Android.

### How to reproduce ?

I use the same code on the computer and it can output A normally, but there is no response on Android. 
![image](https://github.com/user-attachments/assets/c68dc528-02ca-499a-adaa-a2f3cef72810)
![image](https://github.com/user-attachments/assets/e1cf7f91-2def-469e-851b-cee759487a5b)
![image](https://github.com/user-attachments/assets/ee8b6e5d-2676-4125-bf72-a11f654d8dde)
![image](https://github.com/user-attachments/assets/960b6c31-1a9b-42cd-8fcd-9e8e0792728e)

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

I (288) sleep: Enable automatic switching of GPIO sleep configuration
I (295) main_task: Started on CPU0
I (305) main_task: Calling app_main()
I (305) app: USB initialization
W (305) tusb_desc: No Device descriptor provided, using default.
I (365) tusb_desc: 
┌─────────────────────────────────┐
│  USB Device Descriptor Summary  │
├───────────────────┬─────────────┤
│bDeviceClass       │ 239         │
├───────────────────┼─────────────┤
│bDeviceSubClass    │ 2           │
├───────────────────┼─────────────┤
│bDeviceProtocol    │ 1           │
├───────────────────┼─────────────┤
│bMaxPacketSize0    │ 64          │
├───────────────────┼─────────────┤
│idVendor           │ 0x303a      │
├───────────────────┼─────────────┤
│idProduct          │ 0x4009      │
├───────────────────┼─────────────┤
│bcdDevice          │ 0x100       │
├───────────────────┼─────────────┤
│iManufacturer      │ 0x1         │
├───────────────────┼─────────────┤
│iProduct           │ 0x2         │
├───────────────────┼─────────────┤
│iSerialNumber      │ 0x3         │
├───────────────────┼─────────────┤
│bNumConfigurations │ 0x1         │
└───────────────────┴─────────────┘
I (525) TinyUSB: TinyUSB Driver installed
I (525) app: USB initialization DONE
I (525) main_task: Returned from app_main()

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by HiFiPhile** [comment]
Out of scope
