### ISSUE TITLE
Example for CM4 in dual-core RT117x

### ISSUE THREAD

**Issue by mastupristi** [hathach/tinyusb#2849]
### Related area

new example

### Hardware specification

NXP i.MX RT1175

### Is your feature request related to a problem?

There is no example running on core CM4 of an RT1176. I tried to take the code that works successfully on CM7, but it doesn't works on CM4

### Describe the solution you'd like

I would like to have an example running on CM4 of dual-core RT117x.

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
implemented by https://github.com/hathach/tinyusb/pull/2865
