### ISSUE TITLE
dcd dwc2  the number of defined DWC2_EP_COUNT endpoints should be increased by 1

### ISSUE THREAD

**Issue by Maxjta** [hathach/tinyusb#2900]
### Related area

Causes the last endpoint to be unusable。

### Hardware specification

dwc：Number of Device Endpoints (NumDevEps) Indicates the number of device endpoints supported by the core in Device mode in addition to control endpoint 0. The range of this field is 1-15.

### Is your feature request related to a problem?

When there are 8 endpoints, endpoint 0 is included. At this time, there are only 7 defined endpoints, resulting in the last endpoint being unusable.

### Describe the solution you'd like

#define DWC2_EP_COUNT(_dwc2)  ((_dwc2)->ghwcfg2_bm.num_dev_ep + 1)

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

**Comment by hathach** [comment]
thank you, this should be fixed by #2901
