### ISSUE TITLE
(request) finish custom device support

### ISSUE THREAD

**Issue by MiliasColds** [hathach/tinyusb#35]
finish custom device support

I'm working on a project that needs about 1.2 mb/s of bandwidth over USB in circuitpython which uses this USB layer. I am not very experienced with all the ins and outs of USB. I am fairly certain I can implement the bindings between circuit python and tinyusb.

As such it would be very nice if the custom_device support was finished

**Comment by hathach** [comment]
Sorry for late response, have been busy with nrf52 arduino code. The custom endpoints are easy, give me a bit of time, I will add them. Note: you need to update descriptor to include those. Another option is using control transfer ( custom/vendor packet). Anyway, I will do it asap

**Comment by MiliasColds** [comment]
Thanks. I thought the custom was the same as vendor specific from reading through the specifications of usb.

**Comment by hathach** [comment]
Yeah, it is the same, I mean you could either have a pair of in/out endpoints as custom class or use the custom control transfer which require no more endpoints.

**Comment by hathach** [comment]
Vendor class is being added (almost complete) to support webusb example #86

**Comment by hathach** [comment]
@MiliasColds there is more refactor to do, but it is working

**Comment by MiliasColds** [comment]
Thank you for your response.

I look forward to trying it out
