### ISSUE TITLE
midi tud_midi_rx_cb is not working

### ISSUE THREAD

**Issue by chegewara** [hathach/tinyusb#436]
I have working midi code in arduino, and i connected esp32 s2 to web midi app. I know esp32 s2 is configured properly, because device is recognized by windows 10 and linux and i can play midi song from esp to PC on windows. With wrong descriptors drivers installation would fail.
Here is simple code that confirms `tud_midi_rx_cb` callback should be called but is not:
```
void tud_midi_rx_cb(uint8_t itf)
{
    Serial.println(__func__); // <--- this is not called
}

int MIDIusb::available()
{
    return tud_midi_available();
}
```

Here is log from available():
```
available: 16
available: 16
available: 16
available: 16
available: 16
```

**Comment by hathach** [comment]
Please use the bug template those questions are mandatory

**Comment by chegewara** [comment]
> Please use the bug template those questions are mandatory.

No need, i found the cause of issue, thanks.
Callback function is declared in header, but never invoked, so i added it here and now it works:
https://github.com/hathach/tinyusb/blob/master/src/class/midi/midi_device.c#L405

**Comment by hathach** [comment]
> > Please use the bug template those questions are mandatory.
> 
> No need, i found the cause of issue, thanks.
> Callback function is declared in header, but never invoked, so i added it here and now it works:
> https://github.com/hathach/tinyusb/blob/master/src/class/midi/midi_device.c#L405

I am glad you figured it out, seem like it is on of the real bug, or maybe somehow removed in one of the PR. I will re-open it as reminder for fixing.
