### ISSUE TITLE
Current configuration index not saved

### ISSUE THREAD

**Issue by PanRe** [hathach/tinyusb#437]
**Describe what the question is**
I would need to know the current active configuration index, however, this is not saved for now. Right now, `_usbd_dev.configured = cfg_num ? 1 : 0;` is used in usbd.c. It would be possible to save the current index directly as `_usbd_dev.configured = cfg_num;` since anything else than zero is interpreted as true anyway. Am I right on this or is there a more hidden feature why _usbd_dev.configured is 0 or 1 right now?

**Comment by hathach** [comment]
yes, the stack doesn't save config number since it has no usage for now.
