### ISSUE TITLE
Clarify SAM D5x/E5x support?

### ISSUE THREAD

**Issue by jepler** [hathach/tinyusb#440]
Over in CircuitPython we are adding support for the SAM E54.  Based on initial testing works properly with CFG_TUSB_MCU=OPT_MCU_SAMD51.  If no special support is required, perhaps the configuration variable could be renamed (we are saying SAM_D5X_E5X in CircuitPython) or it could be noted in the documentation.  However, it does not appear any change is _required_ at this time.

**Comment by hathach** [comment]
Hi @jepler, I think it is best to have an additional option `OPT_MCU_SAME5X` Other vendors also use the same USB IP for different families. Normally it has a little different in configuration, included header, which is handled by dcd for example https://github.com/hathach/tinyusb/blob/master/src/portable/st/synopsys/dcd_synopsys.c#L35 .

In this case the asf4 does a great work of hardware abstraction, however, it is still beneficial to distinguish them for example, project that doesn't make use of asf4. I will make an PR to add the new MCU option.

**Comment by hathach** [comment]
`OPT_MCU_SAME5X` and `OPT_MCU_SAMD51` are both existed although there is little difference thanks to asf4.
