### ISSUE TITLE
Why return false directly without leaving a callback to decide the result?

### ISSUE THREAD

**Issue by chang196700** [hathach/tinyusb#459]
In file usbd.c:
Why return false directly without leaving a callback to decide the result?

Ref: https://github.com/hathach/tinyusb/blob/0c9932440b794fbdc699df6f0601f6febddedfe5/src/device/usbd.c#L881

**Comment by hathach** [comment]
yeah, since I am too worried that application will use it as index which could overflow the memory since not everyone is aware of this microsoft extension. It should really be on its own callback, and I am too lazy to read and implement the microsoft specs example for that.

**Comment by chang196700** [comment]
I will try to add a weak callback to provide the return value, but it may be a few days later.

**Comment by hathach** [comment]
reopen since this is a legit feature. You could fix it with upcoming PR.

**Comment by pigrew** [comment]
Perhaps just remove that whole if-branch, and always call tud_descriptor_string_cb? The application can handle the descriptor there, if it wants. The application should be doing bounds checking on the index, anyway. The TU_ASSERT would need to be a TU_VERIFY, so it wouldn't trigger a breakpoint if the string is out of bounds.

**Comment by hathach** [comment]
@pigrew yeah, maybe I am over worried about application not being aware of this. But you are right, app should always do bound check anyway. And yes, with that change, the TU_ASSERT should be changed to TU_VERIFY.
