### ISSUE TITLE
Improve documentation for CDC  tud_cdc_write_available()?

### ISSUE THREAD

**Issue by CraigHutchinson** [hathach/tinyusb#460]
**Is your feature request related to a problem? Please describe.**
When transmitting data over CDC the write operation will be partially completed if the transmit buffer cannot fully contain the number of bytes to send. To prevent fragmentation for incomplete data a retry loop is performed until all data is sent.

**Describe the solution you'd like**
I would like to read the remaining capacity of the write buffer as a precondition to check. Only if there is capacity in the transmit buffer for a full message as to avoid getting stuck in a retry loop.

I found 'tud_cdc_write_available' but it is unclear if this function does as I need, maybe just needs rewording:
```
// Return number of characters available for writing
uint32_t tud_cdc_n_write_available (uint8_t itf);
```
i.e. It is not clear if this is returning the number of bytes put into the buffer for writing onto the bus or not.

As confirmed the function is returning remaining free space so this could become:
```
// Return number of free bytes remaining in the transmit buffer 
// @note This may be used to determine the maximum buffsize that can be passed to tud_cdc_write() in a single call
uint32_t tud_cdc_get_tx_buffer_remaining (uint8_t itf);
```

Cheers.

**Comment by duempel** [comment]
> I would like to read the remaining capacity of the write buffer as a precondition to check.

Hello Craig, you've already found the correct function for doing this. `tud_cdc_n_write_available()` actually returns the remaining capacity of items which fit into the dedicated fifo. Since CDC class defines the fifo's item size by 1, this function will return exactly the number of free bytes within the CDC tx buffer.
Do you have any suggestions for a more descriptive name of this function? Maybe _tud_cdc_n_write_free_buffer_size_ fits better than write_available 🤷‍♂️

Since there's already the described function I do not think there is any use introducing a new function to handle those special cases.

> write operation can block if the transmit buffer is full and/or cannot fully contain the number of bytes to send

What's your current setup? Are you using an OS or defined CFG_FIFO_MUTEX? The default setup of CDC will use a not overwriteable fifo. This means that if you put more bytes with `tud_cdc_n_write` than the remaining buffer capacity, the function will just truncate your data and let you loose some bytes (non blocking). If this function blocks the reason might be a locked fifo and not the actual amount of data to be transmitted.

**Comment by CraigHutchinson** [comment]
@duempel Thanks for the response. I hadn't thought changing the function name itself but a improved comment could do it so as to not break existing code that may use it?

If I were to change the name somethign like this seems quite unambiguous:
`tud_cdc_get_tx_buffer_remaining`


> The default setup of CDC will use a not overwriteable fifo. This means that if you put more bytes with `tud_cdc_n_write` than the remaining buffer capacity, the function will just truncate your data and let you loose some bytes (non blocking). If this function blocks the reason might be a locked fifo and not the actual amount of data to be transmitted.

Oh, interesting. I am getting blocked somehow else then. If the PC reading the data from the device goes a bit too slow and doesn't read the data my CDC device update or write appears to have been blocked. I had incorrectly assumed the write function would be blocking to put the data into the buffer.

However, with your clarification it actually could be the code calling the write that is retrying until all the data is written but I will have to check.

**Comment by CraigHutchinson** [comment]
UPDATE: yes there is a loop counting until all the bytes are written so this is my blocking issue. However if I were to break at this condition I would have ended up with fragmented data so as per original-post would prefer not to not star writing if this fragmentation could occur.

**Comment by CraigHutchinson** [comment]
@duempel I updated the description accordingly.

I think updating the comment in the code would help others and would remove ambiguity to this function being either:
1) The number of bytes available for transmitting onto the USB bus (i.e. How many bytes have been written to the buffer)
or
2) The number of bytes available to be written into the buffer (How many bytes can be written into the buffer before it is full)

**Comment by hathach** [comment]
I wouldn't want to change the API name, it is similar to Arduino API, many Arduino user would find it familiar https://www.arduino.cc/reference/en/language/functions/communication/serial/availableforwrite/ 

> @duempel I updated the description accordingly.
> 
> I think updating the comment in the code would help others and would remove ambiguity to this function being either:
> 
> 1. The number of bytes available for transmitting onto the USB bus (i.e. How many bytes have been written to the buffer)
>    or
> 2. The number of bytes available to be written into the buffer (How many bytes can be written into the buffer before it is full)

1 is not technically correct, 2 is better with `The number of bytes available to be written into the FIFO`. Would you mind submitting the PR for this ?
