### ISSUE TITLE
the MSC sd card RW speed is too slow,at about 200K/S

### ISSUE THREAD

**Issue by Thanos-Love-Ironman** [hathach/tinyusb#488]
Hi
MCU:stm32h743
Demo:CDC_MSC_FreeRTOS
I rewrite the msc_disk.c with ST HAL sd card driver.But it's RW speed is too slow,at about 200K/S
Is it the TinyUSB issue or ST HAL sd card driver issue?
what RW speed that the tinyusb msc suppose to be?
Thank you.

**Comment by ladyada** [comment]
you should test ST HAL SD card driver and then report back the max speed for writing you have there.

**Comment by coledd** [comment]
You can improve the USB transfer speed by adjusting the endpoint buffer size in tusb_config.h. It is set very low by default to fit most microcontrollers. But for the H7, you can bump this value up higher to improve throughput. Adjust to your liking, for example:

// MSC Buffer size of Device Mass storage
#define CFG_TUD_MSC_EP_BUFSIZE   4096

**Comment by Thanos-Love-Ironman** [comment]
> you should test ST HAL SD card driver and then report back the max speed for writing you have there.

Thank you. 
The TinyUSB is working well.But the ST HAL SDcard driver cannot working when using dma type function.I am still working on it

**Comment by chegewara** [comment]
Hi,
i am not following tests procedures here, but using my library for esp32 S2 on arduino i could achieve this performance:
1) this example is using RAM disk and internal flash:
![Screenshot from 2020-08-20 10-05-54](https://user-images.githubusercontent.com/1406020/90747862-bae78a00-e2d1-11ea-8edd-2e4a2be3ecce.png)

2) this example is using SD card over SPI:
![Screenshot from 2020-08-20 09-59-23](https://user-images.githubusercontent.com/1406020/90747879-be7b1100-e2d1-11ea-81cc-971a971a7b9a.png)

**Comment by Thanos-Love-Ironman** [comment]
> Hi,
> i am not following tests procedures here, but using my library for esp32 S2 on arduino i could achieve this performance:
> 
> 1. this example is using RAM disk and internal flash:
>    ![Screenshot from 2020-08-20 10-05-54](https://user-images.githubusercontent.com/1406020/90747862-bae78a00-e2d1-11ea-8edd-2e4a2be3ecce.png)
> 2. this example is using SD card over SPI:
>    ![Screenshot from 2020-08-20 09-59-23](https://user-images.githubusercontent.com/1406020/90747879-be7b1100-e2d1-11ea-81cc-971a971a7b9a.png)

That's really fast!
My cdc_msc_freertos project using ST HAL Library sd card driver just can't reach that speed.
In fact,it event cannot transfer data fluently,the RW speed is up to 350KB/S,down to 0KB/S sometimes.

**Comment by chegewara** [comment]
I still think that esp32 s2 can do better. I have to connect LA and see real SPI speed.

**Comment by hathach** [comment]
closed since this is not tinyusb issue but ST HAL driver one, and I don't have any knowledge with ST Hal to help with. If you want to benchmarch the stack performance, you should do it with msc ramdisk by reporting large enough size, and faking msc read/write API.
