### ISSUE TITLE
cdc_msc_freertos project, the tud_cdc_connected() return fail.

### ISSUE THREAD

**Issue by Thanos-Love-Ironman** [hathach/tinyusb#494]
**Set up**
[Mandatory] Provide details of your setup help us to reproduce the issue as quick as possible  
 - **PC OS**   : Windows 10
 - **Board**   : stm32h743,designed by myself
 - **Firmware**: examples/device/cdc_msc_freertos

my project is cdc_smc_freertos project.
The msc device is working well with sd card while cdc function didn't.
tud_cdc_connected() return fail in cdc task which means usb is unconnected,but I do connect the usb with computer.Is it a bug?
Does someone have this issue,too?
Thank you

**Comment by Thanos-Love-Ironman** [comment]
it's working after I remove tud_cdc_connected() in the cdc task.
But it cannot send data by using  tud_cdc_write() after I recieve the data.(buf is non-cacheable)

uint8_t count = tud_cdc_read(buf, sizeof(buf));
 tud_cdc_write(buf,count);

**Comment by hathach** [comment]
which terminal software you are using, try to use other one that set DTR on connection if possible. Currently TinyUSB use that as indication for connected signal. There is lengthy discussion on this #401 . And issue #482 for implementation approach but I currently don't have the time to work on this.

**Comment by hathach** [comment]
closed due to lack of user response.
