### ISSUE TITLE
Need information about porting

### ISSUE THREAD

**Issue by slsvasu348** [hathach/tinyusb#5]
Hi Hathach,

We are trying to port TinyUSB stack with FreeRTOS on NIOS platform. We do have HAL driver of USB ready to be integrated with TInyUSB stack. We need information about which API are required to map with our HAL drivers. Do you have any porting guide?

Thanks,
Vasu.

**Comment by hathach** [comment]
Hi,

Since tinyusb is currently undergone reworking, there is lots of changes ( and still more to come ). If you are working on device stack, you are in luck, since it is 90% done. Please switch to develop branch to work on.

Porting new MCU requires implementing API in these 2 files

https://github.com/hathach/tinyusb/blob/develop/tinyusb/tusb_hal.h
https://github.com/hathach/tinyusb/blob/develop/tinyusb/device/dcd.h

For reference, you may check out other port such as Nordic nrf52 and NXP lpc43xx in portable folder

https://github.com/hathach/tinyusb/tree/develop/tinyusb/portable/nordic/nrf5x
https://github.com/hathach/tinyusb/tree/develop/tinyusb/portable/nxp/lpc43xx_lpc18xx

**Comment by buggins** [comment]
It looks like on current develop branch only device mode portability is implemented.
What is estimated time to finish with host mode refactoring?

**Comment by hathach** [comment]
Indeed, I am working on next major changes, first with the device stack then host stack. Though since I am working on the stack on my free time basic. It is hard to provide an ETA. But I hope to do it as soon as I could. So, no ETA.

**Comment by buggins** [comment]
Thanks! 
So far I'll try to patch ehci.c
For Zynq, it will be necessary to use cache related magic while working with queues/lists (cache flush after change by CPU or cache region invalidating when data is updated by controller)...

**Comment by hathach** [comment]
It sounds a bit complicated, the stack is targeted the MCU, it may not support caching feature you mentioned.

**Comment by hathach** [comment]
@buggins  yeah, what is on develop branch will ended up merged to master later, the OSAL may have more changes as well. There is still lots of works in the progress unfortunately.

**Comment by mad1993** [comment]
@hathach Do you have any documentation available for the APIs required to port tinyUSB? I wanted to have information about what exact functionality control APIs and pipe APIs are implementing (in dcd.h file)?
Any comments would be of great help !

**Comment by hathach** [comment]
If you looking to port the device stack, please check out the develop branch. There is a huge update with improved API there. Here is a example that works with nrf52840. I will merge it eventually
 
https://github.com/hathach/tinyusb/tree/develop/src/portable/nordic/nrf5x

**Comment by mad1993** [comment]
@hathach Thank you for the response. As of now I am trying to port device stack, however I am also looking forward to port host & OTG stack as well. Is there any porting guide available which can help.? 
I went through the developed branch but still facing the same issue of API understanding reagrding its expected functionality to be implemented at place.

**Comment by hathach** [comment]
@mad1993 unfortunately, I haven't got enough time to write a how-to doc for porting. That is terrible, I know. but but.. sighed ~.~ I will try my best here.
- hal should be easy, `uint32_t tusb_hal_millis(void)` is required if your application doesn't has an rtos. (Note Yeah It is not a good name, it should be name osal something, I may change it later on.)
- basically all the function in dcd.h need to be implemented. Note: if your device only has one roothub port, just pass 0 (zero) in place of rhport.

Device API
- dcd_init: called when tusb_init() is invoked
- dcd_set_address() is called when tusb got set device request, you may need to set your prph register for the new address
- dcd_connect/dcd_discconnect : skip it for now.

Event API: these function should be called by your usb interrupt handler to signal the task about the event
- dcd_bus_event: USBD_BUS_EVENT_RESET, USBD_BUS_EVENT_UNPLUGGED is required
- dcd_setup_received(): when received a setup packet
- dcd_xfer_complete(): when a transfer is completed on a specific endpoint (data is queue prio via edpt_xfer() )

Endpoint API: the general flow is open endpoint --> xfer -> xfer_complete event
- open(): will configure an endpoint based on the endpoint descriptor
- xfer(): queue an usb data on an endpoint, when completed, dcd must call xfer_complete above
- control_xfer() is for a DATA/Status stage, when length is zero, it is Status state.

Btw, which MCU you are trying to port. The stack is still under heavy rework. I planned to finalize it, merge to master, and write some doc in future when having more free time.

**Comment by mad1993** [comment]
@hathach are you plaaning to add OTG support in the near future.? As it was mentioned earlier but it is moved to obselete branch. On master branch description only says about Host/Client functionality.

**Comment by hathach** [comment]
@mad1993 yeah, it is still on the plan, since I want tinyusb is a full-fledged stack.  Though, I am a bit busy now. I removed them since it is not yet implemented and would afraid to make people misunderstand the current features. I will
