### ISSUE TITLE
weak symbol relocation error

### ISSUE THREAD

**Issue by HiFiPhile** [hathach/tinyusb#513]
**Set up**
[Mandatory] Provide details of your setup help us to reproduce the issue as quick as possible  
 - **PC OS**   : Windows 10
 - **Board**   : STM32L072
 - **Firmware**: examples/device/cdc_msc

**Describe the bug**

Hi, I'm evaluating Segger Embedded Studio with `gcc` and `segger linker` and I got errors with all functions defined as weak while linking.
For example:
```
case DCD_EVENT_RESUME:
        if (tud_resume_cb) tud_resume_cb();
      break;
```
```Relocation R_ARM_ABS32 to weak symbol 'tud_resume_cb' is invalid```

 At first I though it's a linker bug, after discussion with their technical support, I think it's better to modify weak function calls, at least for `gcc arm eabi`.

The `if(weak_symbol)` relocation is not a valid relocation of an undefined weak symbol accord to the AEABI document.  We don't need to do the "if" at all.  Simply call the weak reference and, if it is satisfied with a weak or strong definition, the linker lays down a call to the function.  If the weak reference is not defined, then the linker replaces the call with a "NOP".

This behavior is specified in the AAELF ("ELF for the ARM Architecture") document:
![eabi](https://user-images.githubusercontent.com/4375114/93064263-9afc7980-f677-11ea-94c0-67ffab6033ed.png)

**Comment by HiFiPhile** [comment]
Meanwhile I'm trying to convince Segger to add this support, since all other linkers I've used have no problem.

**Comment by hathach** [comment]
Hmm, I also use segger embedded studio for debugging occasionally and didn't have any issues with linking weak function. Have you tried out those project in the example https://github.com/hathach/tinyusb/tree/master/examples/device/cdc_msc/ses

Note: some may be out of date and needs update to compile. 

> This behavior is specified in the AAELF ("ELF for the ARM Architecture") document:

I am aware of the direct use of weak function which expanded to NOP. However, I am not sure how other arch would implement that e.g msp430, or xtensa and/or any future ports. Therefore I am opt to the current `if (weakfunc)`

**Comment by HiFiPhile** [comment]
>Hmm, I also use segger embedded studio for debugging occasionally and didn't have any issues with linking weak function.

Do you use segger linker ? I'm using version 5.10a.

It's a demo project about this issue.
[demo.zip](https://github.com/hathach/tinyusb/files/5219079/demo.zip)

**Comment by hathach** [comment]
> > Hmm, I also use segger embedded studio for debugging occasionally and didn't have any issues with linking weak function.
> 
> Do you use segger linker ? I'm using version SES 5.10a with segger-ld 3.04.
> 
> It's a demo project about this issue.
> [demo.zip](https://github.com/hathach/tinyusb/files/5219079/demo.zip)

I will try it later on, meanwhile can you compile with the nrf5x project here https://github.com/hathach/tinyusb/tree/master/examples/device/cdc_msc/ses/nrf5x 

It works with my SES 4.52.

**Comment by HiFiPhile** [comment]
> meanwhile can you compile with the nrf5x project here

I can compile this project since it's using gcc linker.

I think a solution to ensure compatibility between processors is to add a stub function instead using `if'

For example in `usbd.c`, change 
```
// invoke callback
        if (tud_umount_cb) tud_umount_cb();
```
to
```
TU_ATTR_WEAK void tud_umount_cb(){}
  ...
        if (tud_umount_cb) tud_umount_cb();
```

**Comment by hathach** [comment]
> > meanwhile can you compile with the nrf5x project here
> 
> I can compile this project since it's using gcc linker.
> 
> I think a solution to ensure compatibility between processors is to add a stub function instead using `if'
> 
> For example in `usbd.c`, change
> 
> ```
> // invoke callback
>         if (tud_umount_cb) tud_umount_cb();
> ```
> 
> to
> 
> ```
> TU_ATTR_WEAK void tud_umount_cb(){}
>   ...
>         if (tud_umount_cb) tud_umount_cb();
> ```

@HiFiPhile Hmm this is a bit complicated than needed, maybe we can just execute the weak function as you mentioned earlier. However I still need to double check that behavior on some of popular platform, and also try to peak to linux code library implementation such as newlib to see if it does the same. If it does, then we probably don't have to overworry.

**Comment by HiFiPhile** [comment]
> I still need to double check that behavior on some of popular platform.

Maybe we won't support x86 one day ? Because execute weak function can cause segment fault on x86.

**Comment by HiFiPhile** [comment]
It has been fixed in the latest version of SES, with the linker option `--undefined-weak-is-zero`

**Comment by hathach** [comment]
thank you for the update,  I guess we could then close this issue by now ?

**Comment by HiFiPhile** [comment]
Yes, but maybe put a word somewhere ?

**Comment by hathach** [comment]
I guess this issue is good enough, most user could google this out. Or we could point them to this as reference
