### ISSUE TITLE
nrf_drv_usbd_errata.h license is not MIT compatible

### ISSUE THREAD

**Issue by bluelightning32** [hathach/tinyusb#53]
The nrf_drv_usbd_errata.h file included with your package has lots of clauses that contradict your project's MIT license, such as:
```
 * 4. This software, with or without modification, must only be used with a
 *    Nordic Semiconductor ASA integrated circuit.
```

Can you use [nrfx_usb_errata.h](https://github.com/NordicSemiconductor/nrfx/blob/master/drivers/src/nrfx_usbd_errata.h) instead, which has a more permissive license?

**Comment by hathach** [comment]
@bluelightning32 right, thank you for  the issue, this file is added in recent nrfx release. I will do.
