### ISSUE TITLE
Release name

### ISSUE THREAD

**Issue by perigoso** [hathach/tinyusb#556]
Why do the releases contain the date in the name? this is redundant and creates unnecessary clutter

**Comment by hathach** [comment]
I like it that way, what is the reason to not include it ?

**Comment by perigoso** [comment]
It clutters the release names, and eventually the archive links, the date is shown on the releases page right under the name.
But if you like it that way there are no major issues I don't think.

**Comment by hathach** [comment]
I don't see any issue with link or archive as you mentioned. Can you be specific on the name and link by posting it here

**Comment by perigoso** [comment]
You're right it doesn't affect the link, my bad. Again no real issues here, If you have preference for that format.

**Comment by hathach** [comment]
no problem, thanks for paying attention to the detail.
