### ISSUE TITLE
migrate document from doxygen to reStructuredText

### ISSUE THREAD

**Issue by hathach** [hathach/tinyusb#6]
Info https://docs.readthedocs.io/en/latest/getting_started.html

**Comment by tannewt** [comment]
I do a good amount of rST with ReadTheDocs so feel free to ask any questions.

**Comment by hathach** [comment]
@tannewt  thanks Scott, this is more like a reminder for myself. There is already too much code to write ~.~

**Comment by perigoso** [comment]
Is this technically done with #983 ?

**Comment by hathach** [comment]
yeah, I think this can technically be closed. There is always more docs to write much like codes. Thanks again.
