### ISSUE TITLE
Cannot get Audio to write out at full data sample rate

### ISSUE THREAD

**Issue by ndinsmore** [hathach/tinyusb#635]
**Set up**
[Mandatory] Provide details of your setup help us to reproduce the issue as quick as possible  
 - **PC OS**   : osx 10.15 
 - **Board**   : pi pico
 - **Firmware**: examples/device/uac2_audio_headset or examples/device/audio_test

**Describe the bug**
On the pico the callback to fill the transfer buffer are only getting called 200-500 times a second, if I try to up the data size the callback frequency goes down.
When sending data what controls the callback frequency?

**Comment by PanRe** [comment]
Every time the host collected or sent data an interrupt triggers a callback function within the audio driver in which a new transmit for receive or transmit is scheduled.

There is a new design for the audio driver on its rollout, completely redesigning how data is copied. However, i can not say when the PR is finished.

**Comment by ndinsmore** [comment]
This issue was a bug caused by the pico dcd fifo implementation, and a buffer overrun.   It can now be closed.
