### ISSUE TITLE
Readme logo invisible in dark theme

### ISSUE THREAD

**Issue by bnainar** [hathach/tinyusb#673]
![IMG_20210223_112643](https://user-images.githubusercontent.com/59839368/108807350-2fc1b680-75ca-11eb-85a3-d21141df7ae7.jpg)

**Comment by hathach** [comment]
Yeah, I use dark theme as well and have no idea how or which format to make it appeared nicely on both light and dark theme.

**Comment by dhalbert** [comment]
Here is a quick substitute image. The background of the original png is transparent. I made it white and added 10 pixels all around, because it was cropped very tightly.

![tinyusb](https://user-images.githubusercontent.com/2847802/108847382-a0a6a580-75ad-11eb-96d9-280c79389281.png)

**Comment by bnainar** [comment]
@dhalbert, looks good. Make a PR

**Comment by hathach** [comment]
thanks @dhalbert , I have update readme with link to your image :+1: :+1:
