### ISSUE TITLE
SAME70 DCD Support

### ISSUE THREAD

**Issue by HiFiPhile** [hathach/tinyusb#686]
Hi, 

I see you have done the BSP support of SAME70, do you have any plan to add the DCD driver ? :)

I saw there is an implementation in [zephyr](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/usb/device/usb_dc_sam.c) but it's under Apache license.

**Comment by hathach** [comment]
I have it added after purchasing the board. But have no plan at the moment since it is too much work already. My next todo in free time is host stack, it needs a bit more code.

**Comment by HiFiPhile** [comment]
Ok, take your time :)
