### ISSUE TITLE
[Bug] for Metro Express boards .data section is not in bin output file

### ISSUE THREAD

**Issue by dpgeorge** [hathach/tinyusb#69]
**Describe the bug**
`.data` section is not placed in output `.bin` file.

**Set up (please complete the following information):**
 - OS: Linux
 - Board: metro_m0_express and metro_m4_express
 - Firmware Code: any

**To Reproduce**
Build either of the above boards.

**Expected behavior**
`.data` section is expected to be in `.bin` file, but is not.

The `samd21g18a_flash.ld` (and 51) link scripts name the data section `.relocate` yet `examples/rules.mk` is using `data` in the rule to create the `.bin`.  I guess these section names should be made to match each other?

**Comment by hathach** [comment]
thanks @dpgeorge , it is indeed and a bug, there is a pr #68 by zardam that should fixed this issue. I also added uf2 target to make it easier to work with uf2 boatloader board #70

**Comment by dpgeorge** [comment]
Thanks for the fix!  Indeed I was working with uf2 files, so it's nice to have full support for that now in this repo.

**Comment by hathach** [comment]
I am glad that helps, feel free to open other issue if needed ;)
