### ISSUE TITLE
RP2040 Host Stack fails with HID devices

### ISSUE THREAD

**Issue by ristohelkio** [hathach/tinyusb#709]
**Set up**
 - **Board**   : Raspberry Pi Pico with UART tracing via Raspberry Pi 4
 - **Firmware**: /examples/host/cdc_msc_hid
 - **Keyboard**: Generic wireless keypad (Exibel - Provision Technology, Inc)
 - **HUB-keyboard**: Apple

**Describe the bug**
When connecting a keyboard to Pico the process fails at the point where the stack is trying to read the full Device Descriptor. If the Device Descriptor fits into one single packet (bMaxPacketSize0 == 64) the reading is successful. When bMaxPacketSize0 == 8 the stack fails.

**To reproduce**
Connect a keyboard to pico

**Log**
Exibel keypad. When the stack is trying to read an 18 bytes long Device Descriptor it fails. Result is PANIC with 'ep 0 in was already available'
[trace-exibel-keypad.txt](https://github.com/hathach/tinyusb/files/6109326/trace-exibel-keypad.txt)

Additional logs added in file src/portable/raspberrypi/rp2040/rp2040_usb.c (pico_trace replaced with TU_LOG2). The stack seems to receive 8 + 8 + 2 bytes but results in PANIC with 'Data Seq Error ':
[trace-exibel-keypad-detailed.txt](https://github.com/hathach/tinyusb/files/6109385/trace-exibel-keypad-detailed.txt)

In comparison a trace with an Apple keyboard-hub. The hub is connecting properly but when trying to read the Device Descriptor of the keyboard behind the hub, the stack fails. Hub bMaxPacketSize0 is 64 which seems to do the trick.
[trace-apple-keyboard-hub.txt](https://github.com/hathach/tinyusb/files/6109426/trace-apple-keyboard-hub.txt)

**Comment by hathach** [comment]
thanks for the issue, make sure you are running the example with latest master. Though I am not surprized that it doesn't work. It is not your setup or device, it is just the host stack isn't received much of developing time. So far I have reworked usbh and host msc, will do host hid next when I find time.

**Comment by hathach** [comment]
probably be fixed by  raspberrypi/tinyusb#7 based approach.
