### ISSUE TITLE
tud_network_mac_address should be initialized by hardware ID but is const

### ISSUE THREAD

**Issue by maxnet** [hathach/tinyusb#718]
**Is your feature request related to a problem? Please describe.**

https://github.com/hathach/tinyusb/blob/master/examples/device/net_lwip_webserver/src/main.c#L61 mentions that ideally the MAC should be generated by hardware ID.
However the variable is declared const in https://github.com/hathach/tinyusb/blob/master/src/class/net/net_device.h#L62 and in  https://github.com/hathach/tinyusb/blob/master/lib/networking/rndis_reports.c#L39

**Describe the solution you'd like**

Remove "const" so that the MAC can be changed by program in an initialization routine at the start of program that queries the device's serial number and derives MAC from that.

**Comment by hathach** [comment]
yeah, it even has an TODO remove later as well, apparently I plan to remove it. I will check it out later on to see what is best to change.

**Comment by MattMills** [comment]
@hathach Any progress on this? Having an address that needs to be different on every board be const seems like a bad plan...

If there is currently no plans to move the TODO to TODONE, is there any chance the const can be removed?

**Comment by hathach** [comment]
I haven't got time to reviewt net driver, please submit PR if you have suggestion.

**Comment by hathach** [comment]
fixed now

**Comment by Slion** [comment]
I'm pretty sure this should be reopened, see: https://github.com/hathach/tinyusb/pull/1971#issuecomment-2335141214

**Comment by HiFiPhile** [comment]
> Proper fix should be to use a callback.

If you are up to something a PR is welcomed.

**Comment by Slion** [comment]
> If you are up to something a PR is welcomed.

Currently working with an older version of TinyUSB but I'll try to come up with a PR at some point.

**Comment by Slion** [comment]
Ok the fix works if you init the variable early enough. I updated my comment there: https://github.com/hathach/tinyusb/pull/1971#issuecomment-2335141214
