### ISSUE TITLE
midi: bad things happen if device doesn't read midi from host

### ISSUE THREAD

**Issue by jepler** [hathach/tinyusb#735]
We were testing midi on feather m7 rt1011, and @ladyada noticed that if MIDI was being sent out but not acted on by CIrcuitPython, "bad things happened".  On Linux this manifested as being unable to ctrl-c in the REPL and getting messages in the kernel log: `sound midiC4D0: rawmidi drain error (avail = 3934, buffer_size = 4096)`.  Would probably need to throw out some data if buffers fill up?  discarding is better than crashing

**Comment by hathach** [comment]
yeah, we kind of needing a way to drain the midi buffer. However as notice by MIDI user in #618 , dropping data will cause issue with sysEx message rendering the driver unreliable. In practice,  it is rare to have MIDI user that only receive data and do nothing with the data, possibly only happens with test example.

**Comment by ladyada** [comment]
thats ok but it should not take down entire USB subsystem :D 
perhaps it can release unlistened packets?

**Comment by hathach** [comment]
@ladyada hmm, taking down entire stack is not nice, maybe it got some assert() and hanged. I will check it out.

**Comment by ladyada** [comment]
yeah our imx board stopped responding altogether
