### ISSUE TITLE
[Q&A] how to add reasonable cache refresh interface ?

### ISSUE THREAD

**Issue by LucasGit** [hathach/tinyusb#82]
**Here is my question**
i wanna refine my usb host stack now ,cause the cache refresh code is very  violence ,so i was finding some elegant solution or data structure to solve this question ! do you have any ideas ?

**Comment by hathach** [comment]
the host stack needs a rework, I agree.  The API and workflow is not optimal comparing to device stack. But I currently don't have enough time to work on it.

**Comment by LucasGit** [comment]
thanks for your asnswer
