### ISSUE TITLE
Insistent signature of tud_hid_boot_mode_cb()

### ISSUE THREAD

**Issue by dhalbert** [hathach/tinyusb#835]
The signature of `tud_hid_boot_mode_cb()` is

```c
void tud_hid_boot_mode_cb(uint8_t itf, uint8_t boot_mode);
```
However, the `boot_mode` argument is a `bool` taken from:
https://github.com/hathach/tinyusb/blob/2d15e1183064a35cc646a46bddf2b82915114cc8/src/class/hid/hid_device.c#L41-L55
`boot_mode` is passed using this code:
https://github.com/hathach/tinyusb/blob/2d15e1183064a35cc646a46bddf2b82915114cc8/src/class/hid/hid_device.c#L338
So should the signature instead be this?
```c
void tud_hid_boot_mode_cb(uint8_t itf, bool boot_mode);
```
(I was confused for a while due to the `1-` code in the previous routines which flip the sense of the value.)

Obviously this is very minor.

**Comment by hathach** [comment]
thank Dan, I will push an update for this. May need to rename API as well so that I would make more sense. Have got the time to write a example for boot keyboard just yet.
