### ISSUE TITLE
I2S and USB Class Audio

### ISSUE THREAD

**Issue by artouste** [hathach/tinyusb#856]
Hello
I recently used your tinyUSB library through the PICO2040 port of earlephilhower.
  It is very pleasant to use with the MIDI protocol.

Today we easily find I2S ADC modules to experiment (it starts with the small I2S microphones)
Consider adding an audio class to your tnyusb lib to be able to do I2S -> ADC -> PICO -> USB AUDIO. ?

I do not realize the work that this requires of you, but I dream of it: D

Anyway, thank you for everything you have already achieved.

phil Artouste

**Comment by hathach** [comment]
audio is already supported (WIP). The arduino wrapper just does not include it yet, if you are willing to do the work, you could use the bare C API to implement it. Audio is not easy, it will take lots of time.
