### ISSUE TITLE
Is gcc or clang a supported toolchain?

### ISSUE THREAD

**Issue by mithro** [hathach/tinyusb#9]
The README lists the following supported toolchains;
- lpcxpresso
- Keil MDK
- IAR Workbench

I'm guessing that GCC probably already works but isn't included in the list? What about clang?

**Comment by hathach** [comment]
ah, yeah, I am having major changes on develop branch. I am too tired to keep up with these IDE changes and configure. Eventually, there will be makefile (gcc, not sure about clang) and segger embedded studio for debugging. SES is crossplatform and free for non-commercial without code limit, and support lots of mcu. GUI is decent but debugging is very good. There is still lots of works though :(

**Comment by hathach** [comment]
thanks @tannewt  for the anwser
