### ISSUE TITLE
ESP32-S2 compile problem

### ISSUE THREAD

**Issue by josjkasan** [hathach/tinyusb#972]
### Operating System

Windows 10

### Board

ESP32-S2 Dev

### Firmware

TinyUSB library, Arduino IDE, ESP Core 2.00A,

### What happened ?

Hello! Sorry to start new issue, but I waste a lot of time with compile any example. I try Adafruit, Chegewara libraries, but anyway I didn't get any succes. Can you help me with list of all required steps and addons do be able to flash my chip? Or link with tutorial, or advice which IDE to use? Due to fact of using Windows 10, I'm not able to do like described in docs\get started.

### How to reproduce ?

Install library -> open example -> receive error compile ESP32S2

**Comment by hathach** [comment]
Incorrect repo
